'use client';

import { useEffect, useMemo, useState } from 'react';
import { trackEvent } from '@/mresalat/core/analytics';
import { MResalatIcon } from '@/mresalat/core/MResalatIcon';
import { MBazarAssistant, MBazarProductGrid, MBazarProductQuickView, MBazarSearch, MBazarShell } from './MBazarComponents';
import { mbazarCategories, mbazarProducts, sellerById } from './data';
import type { MBazarProduct, MBazarSeller } from './types';

export function MBazarSellerHeader({ seller }: { seller: MBazarSeller }) {
  const hasRating = typeof seller.rating === 'number' && Boolean(seller.reviewCount);
  return <header className="mbazar-seller-header"><div className="mbazar-seller-logo"><MResalatIcon name="seller" size={32} /></div><div><small>عرضه‌کننده در ام‌بازار</small><h1>{seller.name}</h1><p>{seller.description}</p><div className="mbazar-seller-trust"><span><MResalatIcon name="evidence" size={16} />اطلاعات فروشنده از سامانه ام‌بازار</span><span><MResalatIcon name="location" size={16} />{seller.region}</span><span><MResalatIcon name={hasRating ? 'success' : 'help'} size={16} />{hasRating ? `${seller.rating!.toLocaleString('fa-IR')} از ۵ · ${seller.reviewCount!.toLocaleString('fa-IR')} ارزیابی فروشگاه` : 'بدون امتیاز فروشگاه'}</span></div></div></header>;
}

export function MBazarSellerPage({ id, initialQuery = '', unavailable = false }: { id: string; initialQuery?: string; unavailable?: boolean }) {
  const seller = sellerById(id); const [query, setQuery] = useState(initialQuery); const [availableOnly, setAvailableOnly] = useState(false); const [installmentOnly, setInstallmentOnly] = useState(false); const [sort, setSort] = useState<'recommended' | 'price-low'>('recommended'); const [quick, setQuick] = useState<MBazarProduct>();
  useEffect(() => { trackEvent({ event: 'mbazar_seller_opened', surface: 'seller', entityId: seller.id }); }, [seller.id]);
  const sellerProducts = useMemo(() => mbazarProducts.filter((product) => product.seller.id === seller.id), [seller.id]);
  const categories = useMemo(() => mbazarCategories.filter((category) => sellerProducts.some((product) => product.categoryId === category.id)), [sellerProducts]);
  const products = useMemo(() => sellerProducts.filter((product) => (!query || product.title.includes(query)) && (!availableOnly || product.availability !== 'unavailable') && (!installmentOnly || product.installmentEligible)).sort((a, b) => sort === 'price-low' ? a.price.current - b.price.current : 0), [sellerProducts, query, availableOnly, installmentOnly, sort]);
  const search = (value: string) => { setQuery(value); history.pushState(null, '', `/examples/mbazar/seller/${seller.id}?q=${encodeURIComponent(value)}`); };
  if (unavailable || seller.status === 'unavailable') return <MBazarShell active="search"><main className="mbazar-purchase-page"><section className="mbazar-account-error"><MResalatIcon name="seller" size={32} /><h1>فروشگاه در دسترس نیست</h1><p>اطلاعات این عرضه‌کننده در داده نمایشی فعلی پیدا نشد.</p><a className="button button-primary" href="/examples/mbazar">بازگشت به ام‌بازار</a></section></main></MBazarShell>;
  return <MBazarShell active="search"><main className="mbazar-purchase-page mbazar-seller-page"><MBazarSellerHeader seller={seller} /><MBazarAssistant title="درباره محصولات این فروشگاه سؤال دارید؟" prompts={['محصولات پرفروش', 'کالاهای اقساطی', 'شرایط ارسال', 'دسته‌بندی‌ها']} /><section className="mbazar-seller-tools"><MBazarSearch initialQuery={query} onSubmit={search} /><div><button type="button" className={availableOnly ? 'active' : ''} aria-pressed={availableOnly} onClick={() => setAvailableOnly(!availableOnly)}>فقط موجود</button><button type="button" className={installmentOnly ? 'active' : ''} aria-pressed={installmentOnly} onClick={() => setInstallmentOnly(!installmentOnly)}>قابل درخواست اقساطی</button><label>مرتب‌سازی<select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option value="recommended">پیشنهادی</option><option value="price-low">کمترین قیمت</option></select></label></div></section>{categories.length > 0 && <section className="mbazar-seller-categories"><header><h2>دسته‌بندی‌های فروشگاه</h2></header><div>{categories.map((category) => <button type="button" key={category.id} onClick={() => search(category.title)}><MResalatIcon name={category.icon} size={24} /><span><strong>{category.title}</strong><small>{sellerProducts.filter((product) => product.categoryId === category.id).length.toLocaleString('fa-IR')} کالا</small></span></button>)}</div></section>}<section className="mbazar-seller-products"><header><div><small>کالاهای {seller.name}</small><h2>{query ? `نتیجه برای «${query}»` : 'همه محصولات'}</h2></div><span>{products.length.toLocaleString('fa-IR')} کالا</span></header>{products.length ? <MBazarProductGrid products={products} onQuickView={setQuick} /> : <div className="mbazar-inline-empty"><MResalatIcon name="search" size={24} /><span><strong>کالایی پیدا نشد</strong><small>عبارت جستجو یا فیلترها را تغییر دهید.</small></span><button type="button" onClick={() => { setQuery(''); setAvailableOnly(false); setInstallmentOnly(false); }}>پاک کردن فیلترها</button></div>}</section><section className="mbazar-seller-service"><MResalatIcon name="product" size={24} /><div><strong>ارسال و خدمت‌رسانی</strong><p>شرایط هر کالا در صفحه محصول نمایش داده می‌شود. زمان دقیق یا سیاستی خارج از داده قطعی فروشگاه در این دمو ادعا نمی‌شود.</p></div></section><MBazarProductQuickView product={quick} onClose={() => setQuick(undefined)} /></main></MBazarShell>;
}
