'use client';

import Link from 'next/link';
import { useMemo, useState, type FormEvent } from 'react';
import { Badge } from '@/mresalat/core/primitives';
import { MResalatIcon, type MResalatIconName } from '@/mresalat/core/MResalatIcon';
import { Field, Panel, ProductExampleShell, SafeReview, SearchBox, SegmentedTabs, Stepper } from '../product/ProductExampleShell';

const financeActions: Array<{ href: string; label: string; detail: string; icon: MResalatIconName; tone: string }> = [
  { href: '/examples/mhesam/transactions', label: 'تراکنش‌ها', detail: 'جستجو و ردیف‌های پوشانده', icon: 'reports', tone: 'blue' },
  { href: '/examples/mhesam/credit/withdraw', label: 'برداشت اعتبار', detail: 'مبلغ، حساب و مرور امن', icon: 'wallet', tone: 'green' },
  { href: '/examples/mhesam/credit/donate', label: 'اهدای اعتبار', detail: 'گیرنده، بررسی و مبلغ', icon: 'gift', tone: 'violet' },
  { href: '/examples/mhesam/mqr', label: 'MQR', detail: 'QR نمایشی و کنترل حریم خصوصی', icon: 'grid', tone: 'cyan' },
  { href: '/examples/mhesam/vouchers', label: 'بن‌ها', detail: 'فعال، مصرف‌شده و منقضی', icon: 'gift', tone: 'amber' },
  { href: '/examples/mhesam/maghsat', label: 'ام‌اقساط', detail: 'سررسید و پیشرفت نمایشی', icon: 'calendar', tone: 'rose' },
];

export function CreditOverview() {
  const [masked, setMasked] = useState(true);
  return <ProductExampleShell serviceId="mhesam-credit" actions={<button className="button button-secondary" type="button" onClick={() => setMasked(!masked)}><MResalatIcon name={masked ? 'view' : 'lock'} size={17} />{masked ? 'نمایش مقادیر ساختگی' : 'پوشاندن مقادیر'}</button>}><section className="credit-overview"><div className="credit-balance"><small>اعتبار قابل استفاده · دمو</small><strong>{masked ? '••••••••' : '۲۴٬۰۰۰٬۰۰۰'} <span>ریال نمایشی</span></strong><p>این مقدار fixture است و به حساب یا کیف پول واقعی مرتبط نیست.</p><div><Badge tone="success">فعال · دمو</Badge><span>آخرین به‌روزرسانی: اکنون در مرورگر</span></div></div><div className="credit-summary-stack"><article><span>اعتبار رزروشده</span><strong>{masked ? '••••' : '۳٬۲۰۰٬۰۰۰'}</strong></article><article><span>بن فعال</span><strong>۲</strong></article><article><span>اقدام نیازمند توجه</span><strong>۱</strong></article></div></section><section className="finance-action-grid">{financeActions.map((action) => <Link className={`finance-action tone-${action.tone}`} href={action.href} key={action.href}><span><MResalatIcon name={action.icon} size={23} /></span><div><strong>{action.label}</strong><small>{action.detail}</small></div><MResalatIcon name="next" size={17} /></Link>)}</section><Panel title="فعالیت اخیر" eyebrow="کاملاً ساختگی و پوشانده" icon="time"><div className="activity-list"><article><span className="activity-icon incoming"><MResalatIcon name="wallet" size={19} /></span><div><strong>تغییر در اعتبار نمایشی</strong><small>امروز · شناسه DEMO-81</small></div><b>{masked ? '••••' : '+ ۱٬۵۰۰٬۰۰۰'}</b></article><article><span className="activity-icon outgoing"><MResalatIcon name="gift" size={19} /></span><div><strong>مرور اهدای اعتبار</strong><small>هفته گذشته · بدون اجرا</small></div><b>{masked ? '••••' : '۰ ریال اجراشده'}</b></article></div></Panel></ProductExampleShell>;
}

const transactionRows = [
  { id: 'TRX-D-8104', title: 'افزایش اعتبار نمایشی', type: 'credit', date: '۱۴۰۵/۰۶/۰۴', status: 'تکمیل دمو', amount: '+ ••••', source: 'منبع پوشانده' },
  { id: 'TRX-D-8021', title: 'مرور خرید MQR', type: 'purchase', date: '۱۴۰۵/۰۵/۲۸', status: 'در حال بررسی', amount: '− ••••', source: 'پذیرنده ساختگی' },
  { id: 'TRX-D-7988', title: 'بن استفاده‌نشده', type: 'voucher', date: '۱۴۰۵/۰۵/۱۶', status: 'فعال', amount: '••••', source: 'کمپین نمونه' },
  { id: 'TRX-D-7802', title: 'درخواست برداشت متوقف‌شده', type: 'withdraw', date: '۱۴۰۵/۰۴/۲۰', status: 'بدون اجرا', amount: '۰', source: 'حساب ••۴۲' },
];

export function Transactions() {
  const [tab, setTab] = useState('all'); const [query, setQuery] = useState(''); const [selected, setSelected] = useState<(typeof transactionRows)[number]>();
  const rows = useMemo(() => transactionRows.filter((row) => (tab === 'all' || row.type === tab) && (!query || `${row.id} ${row.title}`.toLowerCase().includes(query.toLowerCase()))), [tab, query]);
  return <ProductExampleShell serviceId="mhesam-transactions"><section className="transaction-summary"><article><small>ورودی‌های نمایشی</small><strong>••••</strong><Badge tone="success">۳ ردیف</Badge></article><article><small>خروجی‌های نمایشی</small><strong>••••</strong><Badge tone="warning">۱ ردیف</Badge></article><article><small>ارزش واقعی نمایش‌داده‌شده</small><strong>۰</strong><Badge tone="neutral">همه پوشانده</Badge></article></section><Panel title="تراکنش‌ها" eyebrow="فهرست قابل فیلتر" icon="reports"><div className="transaction-toolbar"><SegmentedTabs value={tab} onChange={setTab} tabs={[{ id: 'all', label: 'همه' }, { id: 'credit', label: 'اعتبار' }, { id: 'purchase', label: 'خرید' }, { id: 'voucher', label: 'بن' }, { id: 'withdraw', label: 'برداشت' }]} /><SearchBox value={query} onChange={setQuery} placeholder="شناسه یا شرح تراکنش…" /></div><div className="filter-grid compact"><Field label="از تاریخ"><input type="date" /></Field><Field label="تا تاریخ"><input type="date" /></Field><Field label="وضعیت"><select defaultValue="all"><option value="all">همه وضعیت‌ها</option><option>در حال بررسی</option><option>فعال</option><option>بدون اجرا</option></select></Field></div><div className="transaction-list">{rows.map((row) => <button type="button" onClick={() => setSelected(row)} key={row.id}><span className={`activity-icon ${row.amount.startsWith('+') ? 'incoming' : 'outgoing'}`}><MResalatIcon name={row.type === 'voucher' ? 'gift' : row.type === 'purchase' ? 'orders' : 'wallet'} size={19} /></span><div><strong>{row.title}</strong><small><bdi dir="ltr">{row.id}</bdi> · {row.date}</small></div><Badge tone={row.status === 'بدون اجرا' ? 'neutral' : row.status === 'در حال بررسی' ? 'warning' : 'success'}>{row.status}</Badge><b dir="ltr">{row.amount}</b></button>)}{rows.length === 0 && <div className="product-empty">تراکنشی با این فیلترها نیست.</div>}</div></Panel>{selected && <aside className="detail-drawer" role="dialog" aria-modal="true" aria-label="جزئیات تراکنش"><button className="icon-button" type="button" aria-label="بستن" onClick={() => setSelected(undefined)}><MResalatIcon name="close" size={20} /></button><Badge tone="info">جزئیات ساختگی</Badge><h2>{selected.title}</h2><dl><div><dt>شناسه</dt><dd dir="ltr">{selected.id}</dd></div><div><dt>تاریخ</dt><dd>{selected.date}</dd></div><div><dt>مبلغ</dt><dd>{selected.amount}</dd></div><div><dt>منبع</dt><dd>{selected.source}</dd></div></dl><p>هیچ داده تراکنش واقعی بارگیری نشده است.</p></aside>}</ProductExampleShell>;
}

export function Mqr() {
  const [revealed, setRevealed] = useState(false);
  return <ProductExampleShell serviceId="mqr"><div className="product-split"><section className="mqr-card"><header><div><small>MQR · شناسه پرداخت نمایشی</small><h2>برای خرید حضوری</h2></div><Badge tone="warning">غیرقابل اسکن</Badge></header><div className={`qr-placeholder large ${revealed ? 'revealed' : ''}`}>{revealed ? <><span /><span /><span /><i /><b /></> : <MResalatIcon name="lock" size={36} />}</div><strong>{revealed ? 'DEMO · NOT SCANNABLE' : 'QR پنهان است'}</strong><button className="button button-secondary" type="button" onClick={() => setRevealed(!revealed)}>{revealed ? 'پنهان‌کردن' : 'نمایش نسخه دمو'}</button></section><Panel title="استفاده امن از MQR" eyebrow="حریم خصوصی" icon="security"><ol className="numbered-guide"><li><span>۱</span><div><strong>فقط نزد پذیرنده معتبر</strong><p>QR واقعی می‌تواند اطلاعات پرداخت را نمایندگی کند.</p></div></li><li><span>۲</span><div><strong>مبلغ را پیش از تأیید ببینید</strong><p>این دمو هیچ مبلغ یا پذیرنده‌ای را دریافت نمی‌کند.</p></div></li><li><span>۳</span><div><strong>تصویر را منتشر نکنید</strong><p>اشتراک‌گذاری QR واقعی می‌تواند خطر امنیتی داشته باشد.</p></div></li></ol><button className="button button-primary" type="button" disabled>ورود به خرید واقعی غیرفعال است</button></Panel></div></ProductExampleShell>;
}

export function AmountPad({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  return <div className="amount-control"><label><span>مبلغ نمایشی (ریال)</span><input dir="ltr" inputMode="numeric" value={value} onChange={(event) => onChange(event.target.value.replace(/\D/g, '').slice(0, 10))} placeholder="0" /></label><div>{['1000000', '3000000', '5000000'].map((amount) => <button type="button" onClick={() => onChange(amount)} key={amount}>{Number(amount).toLocaleString('fa-IR')}</button>)}</div><small>مقدار فقط در حافظه همین صفحه نگه داشته می‌شود.</small></div>;
}

export function CreditWithdrawal() {
  const [step, setStep] = useState(0); const [amount, setAmount] = useState(''); const [account, setAccount] = useState('acct-42');
  return <ProductExampleShell serviceId="credit-withdrawal"><Stepper steps={['مبلغ', 'حساب مقصد', 'مرور و تأیید']} current={step} />{step === 0 && <div className="product-split"><Panel title="مبلغ برداشت" eyebrow="اعتبار موجود · پوشانده" icon="wallet"><div className="masked-summary"><small>اعتبار قابل برداشت</small><strong>•••••••• ریال</strong><span>عدد واقعی در دسترس این دمو نیست.</span></div><AmountPad value={amount} onChange={setAmount} /><button className="button button-primary" type="button" disabled={!amount} onClick={() => setStep(1)}>انتخاب حساب مقصد</button></Panel><Panel title="پیش از ادامه" eyebrow="اثر مالی" icon="warning"><p className="panel-copy">برداشت واقعی، اعتبار را کاهش و درخواست واریز به حساب انتخاب‌شده ایجاد می‌کند. این دمو چنین اثری ندارد.</p></Panel></div>}{step === 1 && <Panel title="حساب مقصد" eyebrow="حساب‌های کاملاً ساختگی" icon="bank"><div className="account-selector" role="radiogroup"><label className={account === 'acct-42' ? 'selected' : ''}><input type="radio" name="account" checked={account === 'acct-42'} onChange={() => setAccount('acct-42')} /><span><strong>حساب نمایشی اصلی</strong><small dir="ltr">IR•• •••• •••• •••• ••42</small></span></label><label className={account === 'acct-17' ? 'selected' : ''}><input type="radio" name="account" checked={account === 'acct-17'} onChange={() => setAccount('acct-17')} /><span><strong>حساب نمایشی دوم</strong><small dir="ltr">IR•• •••• •••• •••• ••17</small></span></label></div><button className="button button-primary" type="button" onClick={() => setStep(2)}>مرور نهایی</button><button className="button button-ghost" type="button" onClick={() => setStep(0)}>بازگشت</button></Panel>}{step === 2 && <SafeReview title="مرور برداشت اعتبار" rows={[{ label: 'مبلغ نمایشی', value: `${Number(amount || 0).toLocaleString('fa-IR')} ریال` }, { label: 'حساب مقصد', value: account === 'acct-42' ? 'حساب ••۴۲' : 'حساب ••۱۷' }, { label: 'اثر احتمالی', value: 'کاهش اعتبار و ایجاد واریز' }, { label: 'اجرای دمو', value: 'صفر؛ هیچ رسید موفقی ساخته نمی‌شود' }]} action="تأیید برداشت واقعی غیرفعال است" />}</ProductExampleShell>;
}

export function CreditDonation() {
  const [step, setStep] = useState(0); const [username, setUsername] = useState(''); const [identifier, setIdentifier] = useState(''); const [purpose, setPurpose] = useState(''); const [amount, setAmount] = useState(''); const [verified, setVerified] = useState(false);
  const verify = (event: FormEvent) => { event.preventDefault(); if (username.length > 2 && identifier.length >= 6) { setVerified(true); setStep(1); } };
  return <ProductExampleShell serviceId="credit-donation"><Stepper steps={['گیرنده', 'مبلغ و هدف', 'مرور اهدا']} current={step} />{step === 0 && <Panel title="گیرنده اعتبار" eyebrow="بررسی ساختگی" icon="profile"><form className="product-form compact-form" onSubmit={verify}><Field label="نام کاربری گیرنده"><input dir="ltr" value={username} onChange={(event) => setUsername(event.target.value)} placeholder="demo-recipient" /></Field><Field label="شناسه ملی / اتباع"><input dir="ltr" value={identifier} onChange={(event) => setIdentifier(event.target.value.replace(/\s/g, '').slice(0, 12))} placeholder="DEMO000001" /></Field><button className="button button-primary" type="submit">بررسی نمایشی گیرنده</button></form></Panel>}{step === 1 && <div className="product-split"><Panel title="مبلغ و هدف" eyebrow={verified ? 'گیرنده نمونه تطبیق داده شد' : ''} icon="gift"><div className="verified-recipient"><MResalatIcon name="success" size={20} /><div><strong>گیرنده ساختگی</strong><small><bdi dir="ltr">{username}</bdi> · •••{identifier.slice(-3)}</small></div><Badge tone="success">Demo verified</Badge></div><AmountPad value={amount} onChange={setAmount} /><Field label="هدف اختیاری"><textarea rows={3} value={purpose} onChange={(event) => setPurpose(event.target.value)} placeholder="برای نمونه: حمایت آموزشی" /></Field><button className="button button-primary" type="button" disabled={!amount} onClick={() => setStep(2)}>مرور اهدا</button></Panel><Panel title="این اقدام چه اثری دارد؟" eyebrow="L3" icon="warning"><p className="panel-copy">در محصول واقعی، اعتبار از حساب شما کم و به گیرنده منتقل می‌شود. نام و شناسه گیرنده باید دوباره مرور شود.</p></Panel></div>}{step === 2 && <SafeReview title="مرور اهدای اعتبار" rows={[{ label: 'گیرنده', value: `@${username} · شناسه •••${identifier.slice(-3)}` }, { label: 'مبلغ', value: `${Number(amount || 0).toLocaleString('fa-IR')} ریال نمایشی` }, { label: 'هدف', value: purpose || 'بدون هدف' }, { label: 'اثر واقعی دمو', value: 'هیچ انتقالی انجام نمی‌شود' }]} action="اهدای واقعی غیرفعال است" />}</ProductExampleShell>;
}

const vouchers = [
  { id: 'V-100', title: 'بن خرید آموزشی', status: 'active', expiry: '۱۴۰۵/۰۹/۳۰', restriction: 'فقط دسته آموزشی · دمو' },
  { id: 'V-088', title: 'بن خدمات سلامت', status: 'expired', expiry: '۱۴۰۴/۱۲/۲۹', restriction: 'منقضی‌شده · دمو' },
  { id: 'V-071', title: 'بن خرید عمومی', status: 'used', expiry: '۱۴۰۵/۰۳/۱۰', restriction: 'مصرف‌شده در داده نمایشی' },
];

export function Vouchers() {
  const [tab, setTab] = useState('active'); const shown = vouchers.filter((voucher) => voucher.status === tab);
  return <ProductExampleShell serviceId="vouchers"><Panel title="بن‌های من" eyebrow="ارزش‌ها پوشانده‌اند" icon="gift"><SegmentedTabs value={tab} onChange={setTab} tabs={[{ id: 'active', label: 'فعال' }, { id: 'used', label: 'مصرف‌شده' }, { id: 'expired', label: 'منقضی' }]} /><div className="voucher-grid">{shown.map((voucher) => <article className={`voucher-card ${voucher.status}`} key={voucher.id}><header><span><MResalatIcon name="gift" size={23} /></span><Badge tone={voucher.status === 'active' ? 'success' : 'neutral'}>{voucher.status === 'active' ? 'فعال' : voucher.status === 'used' ? 'مصرف‌شده' : 'منقضی'}</Badge></header><h3>{voucher.title}</h3><strong>ارزش: •••••• ریال</strong><dl><div><dt>انقضا</dt><dd>{voucher.expiry}</dd></div><div><dt>محدودیت</dt><dd>{voucher.restriction}</dd></div></dl><button className="button button-secondary" type="button" disabled>استفاده / انتقال غیرفعال</button></article>)}</div></Panel></ProductExampleShell>;
}

export function InPersonPurchases() {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('همه');
  const rows = transactionRows.filter((row) => row.type === 'purchase').filter((row) => (!query || row.id.includes(query)) && (status === 'همه' || row.status === status));
  return <ProductExampleShell serviceId="mqr-in-person-purchases"><Panel title="خریدهای حضوری MQR" eyebrow="تاریخچه ساختگی" icon="orders"><div className="transaction-toolbar"><SearchBox value={query} onChange={setQuery} placeholder="شناسه خرید…" /><div className="filter-grid compact"><Field label="وضعیت"><select value={status} onChange={(event) => setStatus(event.target.value)}><option>همه</option><option>در حال بررسی</option><option>تکمیل دمو</option></select></Field><Field label="تاریخ"><input type="date" /></Field></div></div><div className="purchase-history">{rows.map((row) => <article key={row.id}><span><MResalatIcon name="seller" size={21} /></span><div><strong>پذیرنده ساختگی</strong><small><bdi dir="ltr">{row.id}</bdi> · {row.date}</small></div><Badge tone="warning">{row.status}</Badge><b>{row.amount}</b></article>)}{rows.length === 0 && <div className="product-empty">خریدی با این فیلترها وجود ندارد.</div>}</div></Panel></ProductExampleShell>;
}

const installmentFixtures = [
  { title: 'درخواست کالای دیجیتال', ref: 'INS-D-204', status: 'نیازمند تکمیل', progress: 35, due: 'بدون تعهد' },
  { title: 'طرح خرید نمونه', ref: 'INS-D-181', status: 'در حال بررسی', progress: 68, due: 'بدون سررسید واقعی' },
];

export function InstallmentDashboard({ variant }: { variant: 'plus' | 'standard' | 'deferred' }) {
  const isPlus = variant === 'plus'; const isDeferred = variant === 'deferred'; const serviceId = isPlus ? 'maghsat-plus' : isDeferred ? 'mnessieh' : 'maghsat';
  const [tab, setTab] = useState(isPlus ? 'applications' : 'active'); const [query, setQuery] = useState('');
  return <ProductExampleShell serviceId={serviceId}><section className={`installment-hero ${variant}`}><div><span className="eyebrow">{isDeferred ? 'خرید مدت‌دار' : isPlus ? 'مدیریت درخواست و محصول' : 'برنامه اقساط'}</span><h2>{isDeferred ? 'ام‌نسیه؛ پیش از هر تعهد' : isPlus ? 'ام‌اقساط پلاس' : 'ام‌اقساط'}</h2><p>{isDeferred ? 'اهلیت، تسهیلات نمونه و مسیرهای خرید را بدون ایجاد تعهد مرور کنید.' : isPlus ? 'درخواست‌ها و محصولات احتمالی را با فیلترهای نمایشی مدیریت کنید.' : 'وضعیت، پیشرفت و سررسیدهای کاملاً ساختگی را یک‌جا ببینید.'}</p></div><div className="installment-kpi"><small>{isDeferred ? 'اهلیت دمو' : 'تعهد واقعی'}</small><strong>{isDeferred ? 'نیازمند بررسی' : '۰ ریال'}</strong></div></section><Panel title={isDeferred ? 'مسیرهای خرید' : isPlus ? 'درخواست‌های پلاس' : 'طرح‌های اقساط'} eyebrow="بدون پرداخت یا درخواست واقعی" icon="calendar"><div className="transaction-toolbar"><SegmentedTabs value={tab} onChange={setTab} tabs={isPlus ? [{ id: 'applications', label: 'درخواست‌ها' }, { id: 'products', label: 'محصولات' }, { id: 'details', label: 'جزئیات' }] : isDeferred ? [{ id: 'active', label: 'تسهیلات نمونه' }, { id: 'pathways', label: 'مسیر خرید' }, { id: 'info', label: 'شرایط' }] : [{ id: 'active', label: 'فعال' }, { id: 'due', label: 'نزدیک سررسید' }, { id: 'completed', label: 'تکمیل‌شده' }]} /><SearchBox value={query} onChange={setQuery} placeholder="جستجو در داده‌های نمایشی…" /></div><div className="installment-list">{installmentFixtures.filter((item) => !query || `${item.title} ${item.ref}`.includes(query)).map((item) => <article key={`${variant}-${item.ref}`}><header><div><small dir="ltr">{item.ref}</small><h3>{isDeferred ? 'تسهیلات خرید نمونه' : item.title}</h3></div><Badge tone="warning">{isDeferred ? 'غیرمتعهد' : item.status}</Badge></header><div className="progress-track" aria-label={`${item.progress} درصد`}><span style={{ width: `${item.progress}%` }} /></div><dl><div><dt>پیشرفت نمایشی</dt><dd>{item.progress.toLocaleString('fa-IR')}٪</dd></div><div><dt>{isDeferred ? 'وضعیت تعهد' : 'سررسید'}</dt><dd>{item.due}</dd></div></dl><div><button className="button button-secondary" type="button">مشاهده جزئیات</button><button className="button button-primary" type="button" disabled>{isDeferred ? 'تعهد / پرداخت غیرفعال' : isPlus ? 'درخواست / انتخاب محصول غیرفعال' : 'پرداخت غیرفعال'}</button></div></article>)}</div></Panel></ProductExampleShell>;
}

export const mhesamScreens: Record<string, React.ComponentType> = {
  transactions: Transactions,
  mqr: Mqr,
  'credit/withdraw': CreditWithdrawal,
  'credit/donate': CreditDonation,
  vouchers: Vouchers,
  'in-person': InPersonPurchases,
  'maghsat-plus': () => <InstallmentDashboard variant="plus" />,
  maghsat: () => <InstallmentDashboard variant="standard" />,
  mnessieh: () => <InstallmentDashboard variant="deferred" />,
};
