import type { Metadata } from 'next';
import { AppShell } from '@/mresalat/core/AppShell';
import { MResalatIcon } from '@/mresalat/core/MResalatIcon';
import { segments, segmentViews } from '@/mresalat/domains/segments';

export const metadata: Metadata = { title: 'Route QA Index' };

const canonical = [{ label: 'خانه عمومی', href: '/' }, { label: 'انتخاب سگمنت', href: '/segments' }, { label: 'شخص حقیقی · خانه', href: '/segments/individual' }, { label: 'شخص حقیقی · احراز هویت', href: '/segments/individual/identity' }, { label: 'شخص حقیقی · OTP', href: '/segments/individual/otp' }, { label: 'شخص حقیقی · وضعیت', href: '/segments/individual/status' }, { label: 'نوجوان · خانه', href: '/segments/under-18' }, { label: 'نوجوان · اطلاعات', href: '/segments/under-18/child-info' }, { label: 'نوجوان · وضعیت', href: '/segments/under-18/status' }, { label: 'سازمان · خانه', href: '/segments/organization' }, { label: 'سازمان · صاحبان امضاء', href: '/segments/organization/owners' }, { label: 'سازمان · وضعیت', href: '/segments/organization/status' }, { label: 'نمونه‌های اکوسیستم', href: '/examples' }, { label: 'سبد ام‌بازار', href: '/examples/mbazar/cart' }, { label: 'پرداخت ام‌بازار', href: '/examples/mbazar/checkout?step=delivery' }, { label: 'مرکز اقساط ام‌بازار', href: '/examples/mbazar/installments' }, { label: 'سفارش فعال', href: '/examples/mbazar/orders/order-2841' }, { label: 'سفارش تحویل‌شده', href: '/examples/mbazar/orders/order-2480' }, { label: 'سفارش لغوشده', href: '/examples/mbazar/orders/order-2319' }, { label: 'سفارش مشکل‌دار', href: '/examples/mbazar/orders/order-2264' }, { label: 'علاقه‌مندی با افت قیمت', href: '/examples/mbazar/favorites' }, { label: 'درخواست پشتیبانی', href: '/examples/mbazar/support/new?order=order-2264' }, { label: 'ام‌بازار من', href: '/examples/mbazar/profile' }, { label: 'وام ام‌مشاور', href: '/loan' }, { label: 'فروشنده فعال', href: '/seller' }, { label: 'پاسخ RAG', href: '/rag' }, { label: 'عملیات امن', href: '/secure' }, { label: 'Showcase', href: '/showcase' }];

export default function QaPage() {
  return <AppShell active="system"><header className="qa-head"><span className="eyebrow">بازبینی مسیرها</span><h1>Route QA Index</h1><p>مسیرهای نمایشی هسته و ام‌بازار از یک صفحه قابل دسترسی‌اند.</p></header><section className="qa-canonical"><h2>نمونه‌های مرجع</h2><div>{canonical.map((route) => <a href={route.href} key={route.href}>{route.label}<MResalatIcon name="next" size={16} /></a>)}</div></section><div className="qa-route-table"><div className="qa-row qa-row-head"><span>سگمنت</span>{segmentViews.map((view) => <span key={view}>{view === 'home' ? 'خانه' : view === 'services' ? 'خدمات' : 'مسیر'}</span>)}</div>{segments.map((segment) => <div className="qa-row" key={segment.id}><strong><MResalatIcon name={segment.icon} size={16} />{segment.name}</strong>{segmentViews.map((view) => <a href={`/segments/${segment.slug}/${view}`} key={view}>{segment.pages[view].label}<MResalatIcon name="next" size={16} /></a>)}</div>)}</div></AppShell>;
}
