import Link from 'next/link';
import { Badge } from '@/mresalat/core/primitives';
import { MResalatIcon } from '@/mresalat/core/MResalatIcon';
import { serviceCatalogById } from '@/mresalat/domains/service-catalog';
import { exampleDomains, routesForDomain } from './example-route-registry';

function DomainPreview({ domainKey }: { domainKey: (typeof exampleDomains)[number]['key'] }) {
  const services = routesForDomain(domainKey).slice(0, 3).map((route) => serviceCatalogById[route.serviceId]);
  return <div className={`gallery-preview preview-${domainKey}`} aria-hidden="true"><header><i /><i /><i /></header>{domainKey === 'communication' || domainKey === 'mhami' ? <div className="preview-conversation">{services.map((service, index) => <span key={service.id}><b>{service.titleFa.slice(0, 1)}</b><i style={{ width: `${74 - index * 12}%` }} /></span>)}</div> : domainKey === 'mhesam' || domainKey === 'banking' ? <div className="preview-finance"><strong>••••••••</strong><span /><span /><small>Demo balance</small></div> : domainKey === 'rahyar' ? <div className="preview-error"><MResalatIcon name="error" size={28} /><span>404</span></div> : <div className="preview-cards">{services.map((service) => <span key={service.id}><MResalatIcon name={service.icon} size={20} /><i /></span>)}</div>}</div>;
}

export function ProductGallery() {
  return <><section className="examples-product-hero"><div><span className="eyebrow">MResalat product prototypes · 2026 audit</span><h1>۶۹ خدمت، به‌شکل تجربه‌های واقعی محصول</h1><p>از جستجو و فیلتر تا فرم، OTP، گفت‌وگو، درگاه امن و وضعیت خطا؛ همه با داده ساختگی و همان مرز توقف ممیزی‌شده.</p><div><Badge tone="success">۶۹ / ۶۹ مسیر متصل</Badge><Badge tone="info">۱۲ فصل محصول</Badge><Badge tone="neutral">بدون اتصال واقعی</Badge></div></div><aside><strong>Catalog ≠ Examples</strong><p><bdi dir="ltr">/catalog</bdi> شواهد و پوشش را نگه می‌دارد؛ اینجا خودِ تجربه محصول را می‌بینید.</p><Link href="/catalog">مشاهده ردپای ممیزی<MResalatIcon name="next" size={16} /></Link></aside></section><section className="product-gallery" aria-label="دامنه‌های نمونه محصول">{exampleDomains.map((domain, index) => { const routes = routesForDomain(domain.key); return <article className={`product-domain-card accent-${domain.accent}`} key={domain.key}><div className="domain-card-number">{String(index + 1).padStart(2, '0')}</div><DomainPreview domainKey={domain.key} /><header><span><MResalatIcon name={serviceCatalogById[routes[0].serviceId].icon} size={23} /></span><div><h2>{domain.titleFa}</h2><small lang="en" dir="ltr">{domain.titleEn}</small></div><Badge tone="neutral">{routes.length.toLocaleString('fa-IR')} مسیر</Badge></header><p>{domain.description}</p><div className="domain-card-links">{routes.slice(0, 3).map((route) => <Link href={route.href} key={route.serviceId}>{serviceCatalogById[route.serviceId].titleFa}</Link>)}</div><Link className="domain-open" href={domain.href}>ورود به تجربه‌های دامنه<MResalatIcon name="next" size={17} /></Link></article>; })}</section></>;
}
