'use client';

import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Badge } from '@/mresalat/core/primitives';
import { MResalatIcon } from '@/mresalat/core/MResalatIcon';
import { DomainLanding, Field, Panel, ProductExampleShell, SafeReview, SegmentedTabs, Stepper } from '../product/ProductExampleShell';

export function MembershipLanding() {
  return <DomainLanding domainKey="membership" lead={<section className="domain-lead membership-lead"><div><span className="eyebrow">یک هویت، چند زمینه عضویت</span><h2>شروع آگاهانه؛ توقف پیش از داده هویتی</h2><p>چه برای خود، فرزند یا سازمان اقدام کنید، نسخه نمایشی مسیر، پیش‌نیاز و نقطه توقف را قبل از ورود اطلاعات حساس روشن می‌کند.</p></div><ol><li><span>۱</span>شناخت شرایط</li><li><span>۲</span>انتخاب زمینه</li><li><span>۳</span>مرور مدارک</li><li><span>۴</span>توقف امن</li></ol></section>} />;
}

export function IndividualMembership() {
  const [ready, setReady] = useState(false);
  return <ProductExampleShell serviceId="individual-membership"><div className="product-split"><Panel title="عضویت شخص حقیقی" eyebrow="شروع موبایل‌محور" icon="profile"><div className="membership-intro"><div className="device-preview"><MResalatIcon name="product" size={30} /><span>نمای موبایل</span><strong>مرور امن شرایط</strong></div><div><h3>پیش از شروع آماده کنید</h3><ul className="requirement-list"><li><MResalatIcon name="success" size={17} />مرور شرایط سنی و هویتی</li><li><MResalatIcon name="success" size={17} />دسترسی شخص به تلفن همراه خودش</li><li><MResalatIcon name="warning" size={17} />آمادگی مدارک؛ بدون بارگذاری در دمو</li></ul><label className="consent-row"><input type="checkbox" checked={ready} onChange={(event) => setReady(event.target.checked)} /><span>شرایط نمایشی را خواندم و می‌دانم این دمو احراز هویت نمی‌کند.</span></label></div></div></Panel><Panel title="پوسته اطلاعات هویتی" eyebrow="پیش‌نمایش مرحله بعد" icon="evidence"><div className="locked-form" aria-label="فرم قفل‌شده اطلاعات هویتی"><Field label="شماره ملی"><input disabled placeholder="در نسخه نمایشی دریافت نمی‌شود" /></Field><Field label="تاریخ تولد"><input disabled placeholder="— / — / —" /></Field><div className="document-drop locked"><MResalatIcon name="evidence" size={24} /><strong>مدارک شناسایی</strong><small>بارگذاری پیش از شروع احراز هویت غیرفعال است.</small></div><button className="button button-primary" type="button" disabled={!ready}>{ready ? 'مرز ورود اطلاعات رسید — ادامه غیرفعال' : 'ابتدا شرایط را بپذیرید'}</button></div></Panel></div></ProductExampleShell>;
}

export function Under18Membership() {
  const [step, setStep] = useState(0); const [birthDate, setBirthDate] = useState(''); const [nationalId, setNationalId] = useState(''); const [error, setError] = useState('');
  const review = (event: FormEvent) => { event.preventDefault(); if (!birthDate || nationalId.length < 6) { setError('برای مرور نمایشی، تاریخ تولد و یک شناسه ساختگی حداقل ۶ رقمی وارد کنید.'); return; } setError(''); setStep(1); };
  return <ProductExampleShell serviceId="under-18-membership"><Stepper steps={['اطلاعات فرزند', 'مرور استعلام', 'افتتاح حساب و نشانی']} current={step} /><div className="product-split"><Panel title="زمینه سرپرست" eyebrow="حساب والد · داده ساختگی" icon="family"><div className="context-card"><span className="mock-avatar">س</span><div><strong>سرپرست نمایشی</strong><small>زمینه: والد / سرپرست قانونی</small></div><Badge tone="success">پس از ورود</Badge></div><p className="panel-copy">استعلام واقعی فقط پس از احراز هویت سرپرست و دریافت اطلاعات معتبر انجام می‌شود.</p></Panel>{step === 0 ? <Panel title="اطلاعات فرزند" eyebrow="گام ۱ از ۳" icon="child"><form className="product-form" onSubmit={review} noValidate><Field label="تاریخ تولد" helper="برای دمو یک تاریخ ساختگی انتخاب کنید."><input inputMode="numeric" value={birthDate} onChange={(event) => setBirthDate(event.target.value)} placeholder="۱۳۹۵/۰۵/۲۱" /></Field><Field label="شناسه ملی ساختگی" helper="هیچ شناسه‌ای ذخیره نمی‌شود."><input inputMode="numeric" dir="ltr" value={nationalId} onChange={(event) => setNationalId(event.target.value.replace(/\D/g, '').slice(0, 10))} placeholder="0000000000" /></Field>{error && <p className="field-error" role="alert">{error}</p>}<button className="button button-primary" type="submit">مرور پیش از استعلام</button></form></Panel> : <SafeReview title="مرور درخواست استعلام" rows={[{ label: 'زمینه', value: 'سرپرست نمایشی' }, { label: 'تاریخ تولد', value: birthDate }, { label: 'شناسه', value: `••••••${nationalId.slice(-2)}` }, { label: 'ادامه احتمالی', value: 'افتتاح حساب و ثبت نشانی' }]} action="استعلام واقعی انجام نمی‌شود" />}</div></ProductExampleShell>;
}

function AddSignatoryDialog({ onClose }: { onClose: () => void }) {
  const closeRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { closeRef.current?.focus(); const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; document.addEventListener('keydown', escape); return () => document.removeEventListener('keydown', escape); }, [onClose]);
  return <div className="product-dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="product-dialog" role="dialog" aria-modal="true" aria-labelledby="signatory-title"><header><div><small>افزودن امضادار نمایشی</small><h2 id="signatory-title">مشخصات امضادار</h2></div><button ref={closeRef} className="icon-button" type="button" aria-label="بستن" onClick={onClose}><MResalatIcon name="close" size={20} /></button></header><div className="product-form-grid"><Field label="نام کاربری"><input placeholder="demo-signatory" dir="ltr" /></Field><Field label="شناسه ملی"><input placeholder="0000000000" inputMode="numeric" dir="ltr" /></Field><Field label="نقش امضا"><select defaultValue=""><option value="" disabled>انتخاب کنید</option><option>صاحب امضای مجاز</option><option>نماینده سازمان</option><option>مدیرعامل</option></select></Field></div><p className="privacy-note"><MResalatIcon name="security" size={17} />«بررسی» فقط خلاصه را نشان می‌دهد و هیچ استعلامی اجرا نمی‌کند.</p><footer><button className="button button-primary" type="button" onClick={onClose}>مرور و بازگشت</button><button className="button button-ghost" type="button" onClick={onClose}>انصراف</button></footer></section></div>;
}

export function OrganizationMembership() {
  const [dialog, setDialog] = useState(false); const [step, setStep] = useState(0); const addSignatoryRef = useRef<HTMLButtonElement>(null);
  const closeDialog = () => { setDialog(false); requestAnimationFrame(() => addSignatoryRef.current?.focus()); };
  return <ProductExampleShell serviceId="organization-membership"><Stepper steps={['معرفی سازمان', 'امضاداران', 'اطلاعات سازمان', 'مرور ثبت']} current={step} /><Panel title="درخواست عضویت سازمانی" eyebrow="مدیریت امضاداران" icon="organization" actions={<button ref={addSignatoryRef} className="button button-primary" type="button" onClick={() => setDialog(true)}><MResalatIcon name="add" size={17} />افزودن امضادار</button>}><div className="signatory-list"><article><span className="mock-avatar">ن</span><div><strong>امضادار نمونه</strong><small><bdi dir="ltr">demo-owner</bdi> · شناسه ••••۲۱</small></div><Badge tone="warning">نیازمند بررسی</Badge><button type="button" onClick={() => setDialog(true)}>ویرایش</button></article></div><div className="organization-actions"><button className="button button-secondary" type="button" onClick={() => setStep(2)}>پیش‌نمایش اطلاعات سازمان</button><span>ثبت و بررسی واقعی انجام نمی‌شود.</span></div></Panel>{step >= 2 && <Panel title="اطلاعات سازمان" eyebrow="پیش‌نمایش گام ۳" icon="evidence"><div className="product-form-grid"><Field label="نام سازمان"><input placeholder="سازمان نمونه رسالت" /></Field><Field label="نوع شخصیت حقوقی"><select defaultValue=""><option value="" disabled>انتخاب کنید</option><option>شرکت</option><option>مؤسسه</option><option>تعاونی</option></select></Field><Field label="شناسه ثبت"><input placeholder="در دمو ذخیره نمی‌شود" /></Field></div><SafeReview rows={[{ label: 'امضاداران', value: '۱ مورد نمایشی' }, { label: 'وضعیت بررسی', value: 'انجام نشده' }, { label: 'اثر ثبت', value: 'ایجاد درخواست عضویت سازمانی' }]} action="تأیید و ثبت واقعی غیرفعال است" /></Panel>}{dialog && <AddSignatoryDialog onClose={closeDialog} />}</ProductExampleShell>;
}

export function MembershipTracking() {
  const [type, setType] = useState('individual'); const [query, setQuery] = useState('MR-DEMO-204'); const found = query.trim().length >= 5;
  return <ProductExampleShell serviceId="membership-request-tracking"><Panel title="پیگیری درخواست عضویت" eyebrow="فقط خواندنی · داده ساختگی" icon="time"><SegmentedTabs value={type} onChange={setType} tabs={[{ id: 'individual', label: 'شخص حقیقی' }, { id: 'child', label: 'زیر ۱۸ سال' }, { id: 'organization', label: 'سازمانی' }]} /><form className="tracking-search" onSubmit={(event) => event.preventDefault()}><Field label="کد پیگیری نمایشی"><input dir="ltr" value={query} onChange={(event) => setQuery(event.target.value)} /></Field><button className="button button-primary" type="submit">نمایش وضعیت</button></form>{found ? <div className="tracking-result"><header><div><small>کد <bdi dir="ltr">{query}</bdi></small><h3>{type === 'organization' ? 'عضویت سازمانی' : type === 'child' ? 'عضویت زیر ۱۸ سال' : 'عضویت شخص حقیقی'}</h3></div><Badge tone="warning">نیازمند تکمیل</Badge></header><ol className="status-timeline"><li className="done"><span /><div><strong>درخواست آغاز شد</strong><small>تاریخ نمونه · ۱۴۰۵/۰۶/۰۲</small></div></li><li className="current"><span /><div><strong>مدارک نیازمند تکمیل است</strong><small>یک مدرک هویتی در محصول واقعی بررسی می‌شود.</small></div></li><li><span /><div><strong>بررسی نهایی</strong><small>هنوز آغاز نشده است.</small></div></li></ol><div className="next-action"><MResalatIcon name="warning" size={20} /><div><strong>اقدام بعدی</strong><p>در محصول واقعی، مدارک ناقص را تکمیل کنید. این دمو فایل نمی‌گیرد.</p></div><button type="button" disabled>تکمیل مدارک</button></div></div> : <div className="product-empty" role="status">برای نمایش نتیجه، کد پیگیری نمایشی را کامل کنید.</div>}</Panel></ProductExampleShell>;
}

export const membershipScreens: Record<string, React.ComponentType> = {
  individual: IndividualMembership,
  'under-18': Under18Membership,
  organization: OrganizationMembership,
  tracking: MembershipTracking,
};
