export type ComponentInventoryItem = {
  category: 'Foundations' | 'Core' | 'Navigation' | 'AI' | 'RAG / Trust' | 'Journeys' | 'Secure' | 'Templates' | 'Motion' | 'Marketplace' | 'Documentation';
  name: string;
  purpose: string;
  variants: string[];
  states: string[];
};

export const componentInventory: ComponentInventoryItem[] = [
  { category: 'Foundations', name: 'BrandLogo', purpose: 'نمایش دارایی رسمی ام‌رسالت', variants: ['full', 'compact', 'light surface'], states: ['light', 'dark'] },
  { category: 'Foundations', name: 'MResalatIcon', purpose: 'نگاشت معنایی آیکون‌های Lucide', variants: ['16', '20', '24', '32'], states: ['active', 'inactive', 'semantic'] },
  { category: 'Foundations', name: 'ThemeToggle', purpose: 'انتخاب و نگهداری پوسته', variants: ['light', 'dark', 'system'], states: ['persisted', 'system-synced'] },
  { category: 'Core', name: 'Button', purpose: 'اقدام‌های استاندارد سیستم', variants: ['primary', 'secondary', 'danger'], states: ['default', 'hover', 'focus', 'disabled'] },
  { category: 'Core', name: 'Badge', purpose: 'برچسب وضعیت و دسته‌بندی', variants: ['info', 'success', 'warning', 'danger', 'neutral'], states: ['static'] },
  { category: 'Core', name: 'Alert', purpose: 'بازخورد و پیام قابل بازیابی', variants: ['info', 'success', 'warning', 'danger'], states: ['status', 'alert'] },
  { category: 'Navigation', name: 'AppShell', purpose: 'هدر، ناوبری دسکتاپ و موبایل', variants: ['desktop', 'mobile floating'], states: ['active route', 'dark theme'] },
  { category: 'AI', name: 'AssistantShell', purpose: 'ورودی و زمینه‌سازی دستیار', variants: ['hero', 'context', 'compact'], states: ['idle', 'focused'] },
  { category: 'AI', name: 'SmartAssistant3D', purpose: 'ربات سه‌بعدی شفاف با نمایشگر نورانی، مفصل‌های دست خواناتر و نگاه آگاه از کل صفحه', variants: ['complete', 'portrait', 'transparent WebGL', 'matching static fallback'], states: ['idle', 'greeting', 'listening', 'thinking', 'explaining', 'happy', 'warning', 'uncertain', 'handoff'] },
  { category: 'AI', name: 'SmartAssistantAvatar', purpose: 'پرتره سبک همان شخصیت در رابط‌های فشرده', variants: ['32', '40', '48', '64', '96'], states: ['eight emotions', 'static optimized'] },
  { category: 'AI', name: 'SmartAssistantCanvas', purpose: 'صحنه کم‌هزینه React Three Fiber و مدل انسان‌نمای کدنویسی‌شده', variants: ['complete camera', 'portrait camera'], states: ['animated', 'local gaze', 'neutral reset', 'reduced', 'page hidden paused'] },
  { category: 'AI', name: 'Assistant3DDemo', purpose: 'مرور تعاملی قاب‌ها، حالت‌ها و اندازه‌های دستیار', variants: ['mode controls', 'emotion controls', 'avatar sizes'], states: ['two modes', 'nine emotions', 'pointer tracking'] },
  { category: 'AI', name: 'SegmentAIEntry', purpose: 'ورودی اصلی سگمنت با پرسش فارسی، پاسخ قطعی نمایشی و پیوند اقدام', variants: ['individual compact', 'youth featured mascot', 'organization professional'], states: ['idle', 'listening', 'thinking', 'answer', 'uncertain', 'handoff'] },
  { category: 'RAG / Trust', name: 'SourceCitation', purpose: 'منبع و شواهد قابل گسترش', variants: ['official knowledge', 'live data'], states: ['collapsed', 'expanded'] },
  { category: 'RAG / Trust', name: 'TrustLegend', purpose: 'راهنمای منشأ و نقش اطلاعات', variants: ['official', 'live', 'AI', 'recommendation'], states: ['light', 'dark'] },
  { category: 'RAG / Trust', name: 'UncertainAnswer', purpose: 'عدم قطعیت و درخواست شفاف‌سازی', variants: ['insufficient evidence'], states: ['clarify', 'handoff'] },
  { category: 'RAG / Trust', name: 'HumanHandoff', purpose: 'انتقال زمینه‌دار به کارشناس', variants: ['with summary'], states: ['ready to handoff'] },
  { category: 'Journeys', name: 'ProcessReviewWizard', purpose: 'مرور افقی و سبک مسیر', variants: ['compact', 'standard', 'featured'], states: ['completed', 'current', 'upcoming'] },
  { category: 'Journeys', name: 'ServicePageTemplate', purpose: 'قالب کامل معرفی و مسیر خدمت', variants: ['service-config driven'], states: ['informational', 'next action'] },
  { category: 'Journeys', name: 'SegmentHero', purpose: 'ورودی متمایز و متناسب با نوع عضویت', variants: ['formal', 'youth with mascot', 'organizational'], states: ['light', 'dark', 'mobile', 'desktop'] },
  { category: 'Journeys', name: 'SegmentActionCard', purpose: 'اقدام اصلی متناسب با هر سگمنت', variants: ['service', 'procedure'], states: ['default', 'hover', 'focus'] },
  { category: 'Journeys', name: 'OtpInput', purpose: 'ورود دسترس‌پذیر کد یک‌بارمصرف', variants: ['five digit', 'localized digits'], states: ['empty', 'typing', 'complete'] },
  { category: 'Journeys', name: 'SegmentStatusPanel', purpose: 'وضعیت درخواست و اقدام بعدی در سه مسیر عضویت', variants: ['individual', 'youth', 'organization', 'compact'], states: ['completed', 'current', 'upcoming'] },
  { category: 'Journeys', name: 'ActiveJourneyCard', purpose: 'نمایش فرایند فعال، مرحله فعلی، پیشرفت و اقدام بعدی', variants: ['standard', 'compact'], states: ['active', 'waiting', 'completed'] },
  { category: 'Templates', name: 'SegmentHomeShell', purpose: 'ترکیب مشترک خانه پس از ثبت‌نام با اولویت‌بندی مستقل هر سگمنت', variants: ['individual', 'under-18', 'organization'], states: ['AI first', 'responsive', 'light', 'dark'] },
  { category: 'Journeys', name: 'ChildInfoPanel', purpose: 'ثبت اطلاعات نوجوان با راهنمای سرپرست', variants: ['route dialog', 'showcase embedded'], states: ['idle', 'verified', 'focus trapped'] },
  { category: 'Journeys', name: 'AddOwnerPanel', purpose: 'افزودن صاحب امضاء سازمانی', variants: ['route dialog', 'showcase embedded'], states: ['idle', 'verified', 'focus trapped'] },
  { category: 'Secure', name: 'SecureActionFlow', purpose: 'اقدام L3 با تأیید و احراز قوی', variants: ['success', 'failure'], states: ['explain', 'confirm', 'step-up', 'receipt'] },
  { category: 'Templates', name: 'SegmentExperience', purpose: 'ترکیب سه صفحه از تنظیم سگمنت', variants: ['home', 'services', 'journey'], states: ['discovery', 'guided', 'operational', 'family', 'young', 'care'] },
  { category: 'Motion', name: 'ParallaxLayer', purpose: 'عمق فضایی محدود و کم‌هزینه', variants: ['restrained', 'young enhanced'], states: ['pointer active', 'reduced motion disabled'] },
  { category: 'Marketplace', name: 'MarketplaceContext', purpose: 'نمایش مقصد ارسال و فروشگاه انتخاب‌شده', variants: ['standard', 'compact'], states: ['shared mock context', 'light', 'dark'] },
  { category: 'Marketplace', name: 'MBazarSearch', purpose: 'ورودی متنی، صوتی و نیازمحور کشف کالا', variants: ['default', 'hero'], states: ['empty', 'typing', 'results'] },
  { category: 'Marketplace', name: 'MBazarCategoryCard', purpose: 'ورودی خوانا و واکنش‌گرا به دسته کالا', variants: ['four semantic tones'], states: ['default', 'hover', 'focus'] },
  { category: 'Marketplace', name: 'MBazarProductCard', purpose: 'نمایش استاندارد هویت، قیمت و وضعیت خرید کالا', variants: ['carousel', 'grid', 'list', 'recommendation'], states: ['available', 'limited', 'installment eligible'] },
  { category: 'Marketplace', name: 'PriceDisplay', purpose: 'قیمت فارسی یکسان بر پایه تومان', variants: ['default', 'compact'], states: ['regular', 'discounted'] },
  { category: 'Marketplace', name: 'PurchaseModeBadge', purpose: 'نمایش برجسته امکان درخواست خرید اقساطی', variants: ['eligible'], states: ['visible', 'omitted'] },
  { category: 'Marketplace', name: 'MBazarFilterBar', purpose: 'فیلترهای سریع و ورودی فیلتر کامل', variants: ['inline', 'mobile scroll'], states: ['active filters', 'default'] },
  { category: 'Marketplace', name: 'MBazarProductQuickView', purpose: 'پیش‌نمایش پاسخ‌گو پیش از ورود به جزئیات', variants: ['desktop drawer', 'mobile bottom sheet'], states: ['open', 'closed', 'escape dismissal'] },
  { category: 'Marketplace', name: 'QuantityControl', purpose: 'تغییر امن تعداد کالا با محدودیت موجودی', variants: ['cart', 'showcase'], states: ['minimum', 'maximum', 'editable'] },
  { category: 'Marketplace', name: 'MBazarCartSummary', purpose: 'محاسبه و نمایش جمع، تخفیف، ارسال و مبلغ نهایی', variants: ['cart', 'checkout'], states: ['populated', 'empty'] },
  { category: 'Marketplace', name: 'PaymentModeSelector', purpose: 'انتخاب برجسته پرداخت نقدی یا درخواست اقساط', variants: ['two-branch'], states: ['cash', 'installment', 'unselected'] },
  { category: 'Marketplace', name: 'DeliveryAddressCard', purpose: 'انتخاب دسترس‌پذیر آدرس تحویل', variants: ['address'], states: ['selected', 'default'] },
  { category: 'Marketplace', name: 'InstallmentEligibilityPanel', purpose: 'نمایش نتیجه قطعی سیستم جدا از توضیح هوش مصنوعی', variants: ['eligible', 'conditional', 'unknown', 'ineligible'], states: ['system result', 'AI explanation'] },
  { category: 'Marketplace', name: 'InstallmentPlanCard', purpose: 'مقایسه کارت‌محور طرح‌های نمایشی اقساط', variants: ['6 months', '12 months', '18 months'], states: ['selected', 'default'] },
  { category: 'Marketplace', name: 'InstallmentRequestCard', purpose: 'نمایش وضعیت، پیشرفت و اقدام بعدی درخواست', variants: ['action required', 'reviewing', 'ready', 'completed'], states: ['progress', 'next action'] },
  { category: 'Marketplace', name: 'MBazarOrderCard', purpose: 'اولویت‌دهی وضعیت فعلی و اقدام بعدی سفارش', variants: ['single seller', 'multi seller'], states: ['active', 'delivered', 'cancelled', 'issue'] },
  { category: 'Marketplace', name: 'MBazarOrderStatus', purpose: 'ترجمه وضعیت سیستمی به زبان خریدار', variants: ['compact', 'prominent'], states: ['seven order statuses'] },
  { category: 'Marketplace', name: 'MBazarOrderProgress', purpose: 'نمایش معنایی مراحل قطعی مرسوله', variants: ['six milestones'], states: ['completed', 'current', 'upcoming'] },
  { category: 'Marketplace', name: 'MBazarFulfillmentGroup', purpose: 'تفکیک مرسوله و پیشرفت هر فروشگاه', variants: ['independent seller parcel'], states: ['preparing', 'in transit', 'delivered', 'failed'] },
  { category: 'Marketplace', name: 'MBazarFavoriteCard', purpose: 'مقایسه قیمت ذخیره‌شده با قیمت و موجودی فعلی', variants: ['product card composition'], states: ['price down', 'price up', 'limited', 'unavailable'] },
  { category: 'Marketplace', name: 'MBazarAddressCard', purpose: 'مدیریت آدرس تحویل مشترک با Checkout', variants: ['default', 'secondary'], states: ['editable', 'deletable', 'protected default'] },
  { category: 'Marketplace', name: 'MBazarReviewCard', purpose: 'نمایش نظر محصول مستقل از اعتبار فروشگاه', variants: ['rating with text'], states: ['submitted'] },
  { category: 'Marketplace', name: 'MBazarRatingInput', purpose: 'انتخاب امتیاز دسترس‌پذیر با صفحه‌کلید', variants: ['one to five'], states: ['empty', 'selected', 'focused'] },
  { category: 'Marketplace', name: 'MBazarSupportCaseCard', purpose: 'وضعیت و اقدام بعدی درخواست پشتیبانی', variants: ['order linked'], states: ['created', 'in review', 'waiting', 'resolved'] },
  { category: 'Marketplace', name: 'MBazarProfileGroup', purpose: 'گروه‌بندی وظیفه‌محور حساب خریدار', variants: ['purchase', 'account', 'support'], states: ['with count', 'without count'] },
  { category: 'Marketplace', name: 'MBazarSellerHeader', purpose: 'هویت و حقایق اعتماد عرضه‌کننده برای خریدار', variants: ['rated', 'unrated'], states: ['marketplace provider', 'unavailable'] },
  { category: 'Navigation', name: 'UserContextSwitcher', purpose: 'تغییر زمینه نقش در یک هویت مشترک', variants: ['desktop dropdown', 'mobile sheet'], states: ['open', 'selected', 'escape', 'restored'] },
  { category: 'Secure', name: 'PermissionState', purpose: 'نمایش قابل فهم امکان مشاهده یا اقدام پیش از تعامل', variants: ['seven semantic states'], states: ['allowed', 'view only', 'approval', 'step up', 'unavailable'] },
  { category: 'Journeys', name: 'ApprovalRequestCard', purpose: 'مرور منبع و اثر درخواست پیش از تصمیم', variants: ['parent', 'organization'], states: ['pending', 'approved', 'rejected'] },
  { category: 'Journeys', name: 'NextBestAction', purpose: 'نمایش اقدام اولویت‌دار متناسب با زمینه', variants: ['info', 'warning', 'success'], states: ['approval', 'expiry', 'journey'] },
  { category: 'Navigation', name: 'ChildSelector', purpose: 'انتخاب زیرزمینه فرزند در نقش والد', variants: ['buttons', 'route links'], states: ['Arya', 'Sara', 'selected'] },
  { category: 'Journeys', name: 'CrossServiceContextMarker', purpose: 'حفظ نشان زمینه میان خدمات اکوسیستم', variants: ['youth goal', 'organization credit'], states: ['active'] },
  { category: 'Documentation', name: 'CodeExample', purpose: 'نمونه کد بازشونده و قابل کپی', variants: ['details panel'], states: ['collapsed', 'expanded', 'copied'] },
  { category: 'Documentation', name: 'GridLayoutDemo', purpose: 'نمایش تعاملی شبکه واقعی صفحه', variants: ['12-column', '4-column mobile'], states: ['overlay shown', 'overlay hidden'] },
];
