export const showcaseSnippets = {
  brand: `<BrandLogo />\n<BrandLogo compact />\n<BrandLogo light />`,
  icon: `<MResalatIcon name="loan" size={20} />\n<MResalatIcon name="next" size={16} label="ادامه" />`,
  controls: `<Button>اقدام اصلی</Button>\n<Button tone="danger">اقدام حساس</Button>\n<Badge tone="success">تکمیل شده</Badge>`,
  alerts: `<Alert tone="warning" title="اطلاعات بیشتری لازم است">\n  فقط یک سؤال روشن‌کننده پاسخ دهید.\n</Alert>`,
  assistant: `<AssistantShell variant="hero" />\n<AssistantShell variant="context" />\n<AssistantShell variant="compact" />`,
  trust: `<TrustLegend />\n<SourceCitation source={source} />\n<UncertainAnswer />\n<HumanHandoff />`,
  journey: `<ProcessReviewWizard\n  title="درخواست وام"\n  steps={steps}\n  progress={48}\n  variant="featured"\n  currentAction={{ label: 'تکمیل مدرک', href: '/loan' }}\n/>`,
  secure: `<SecureActionFlow action={secureAction} />`,
  navigation: `<AppShell active="examples">\n  {children}\n</AppShell>`,
  motion: `<ParallaxLayer strength={10}>\n  <ServiceCard />\n</ParallaxLayer>`,
  segment: `<SegmentExperience\n  segment={segmentBySlug['loan-applicant']}\n  view="journey"\n/>`,
  assistant3d: `<SmartAssistant3D mode="complete" emotion="greeting" />\n<SmartAssistant3D mode="portrait" emotion="listening" />\n<SmartAssistantAvatar size={48} emotion="happy" />\n\n// Transparent, non-essential WebGL character with a matching static fallback.\n// Important labels and answers stay in accessible HTML.\n// emotion: idle | greeting | listening | thinking | explaining\n// happy | warning | uncertain | handoff`,
  segmentPhaseTwo: `<SegmentHomeShell\n  segment="individual"\n  aiEntry={<SegmentAIEntry segment="individual" assistantMode="featured" />}\n>\n  <ActiveJourneyCard journey={journey} segment="individual" />\n</SegmentHomeShell>\n\n// Deterministic Persian demo Q&A; no production LLM or customer data.`,
  grid: `.page-container {\n  width: min(calc(100% - 48px), 1180px);\n}\n\n@media (max-width: 640px) {\n  .page-container { width: calc(100% - 28px); }\n}`,
  mbazar: `<MarketplaceContext />\n<MBazarProductCard product={product} variant="grid" />\n<MBazarFavoriteCard favorite={favorite} />\n<MBazarOrderCard order={order} />\n<MBazarOrderStatus status="preparing" prominent />\n<MBazarOrderProgress milestones={group.milestones} />\n<MBazarFulfillmentGroup group={group} order={order} />\n<MBazarAddressCard address={address} />\n<MBazarReviewCard review={review} />\n<MBazarRatingInput value={4} onChange={setRating} />\n<MBazarSupportCaseCard supportCase={supportCase} />\n<MBazarSellerHeader seller={seller} />`,
} as const;
