import type { ComponentProps, ReactNode } from 'react';
import { componentInventory } from '@/mresalat/core/component-inventory';
import { MResalatIcon, iconGalleryNames } from '@/mresalat/core/MResalatIcon';
import { MResalatServiceIcon as BaseMResalatServiceIcon } from '@/mresalat/core/MResalatServiceIcon';
import { ecosystemIdentityServices, ecosystemServiceById } from '@/mresalat/domains/ecosystem';
import { segments } from '@/mresalat/domains/segments';
import { serviceCatalog, serviceCatalogChapters } from '@/mresalat/domains/service-catalog';
import { exampleDomains, exampleRoutes } from '@/mresalat/examples/product/example-route-registry';
import {
  BrandLockup,
  Callout,
  Figure,
  Ltr,
  PageTitle,
  RiskBadge,
  ScreenshotFigure,
  SectionCover,
  Stat,
  TokenSwatch,
} from './components';
import { brandTokens, catalogBookFacts, catalogBookMeta, lightDarkTokens, publicationSections, trustTokens } from './data';

function MResalatServiceIcon(props: ComponentProps<typeof BaseMResalatServiceIcon>) {
  return <BaseMResalatServiceIcon {...props} eager />;
}

export type FullPageSpec = {
  key: string;
  sectionKey: string;
  sectionTitle: string;
  tone?: 'paper' | 'soft' | 'ink' | 'cyan';
  className?: string;
  content: ReactNode;
};

const sectionStatements = [
  'سیستم از خوانایی فارسی، اعتماد، شفافیت و کنترل ریسک آغاز می‌شود؛ نه از فهرست کامپوننت‌ها.',
  'هویت ام‌رسالت باید در هر اندازه و روی هر سطح، روشن، رسمی و بدون بازسازی سلیقه‌ای باقی بماند.',
  'رنگ نام‌گذاری فنی ثابت دارد، اما مقدار آن برای حفظ معنا و خوانایی در روشن و تیره تغییر می‌کند.',
  'تایپوگرافی فارسی زمانی بالغ است که عدد، تاریخ، مبلغ و رشته فنی را نیز بدون آشفتگی جهت نمایش دهد.',
  'شبکه و فاصله، ریتم مشترک تجربه را از موبایل تا دسکتاپ حفظ می‌کنند.',
  'آیکون عملکرد را توضیح می‌دهد؛ هویت خدمت، مالکیت و مقصد را معرفی می‌کند.',
  'اجزای پایه کم‌تعداد، روشن و ترکیب‌پذیرند و حالت‌های خود را صریح نمایش می‌دهند.',
  'پوسته محصول زمینه ثابت می‌سازد تا کاربر در میان دامنه‌های اکوسیستم گم نشود.',
  'دستیار یک راهنمای رفتاری است؛ حالت، نگاه و حرکت آن باید به فهم فرایند کمک کند.',
  'هر پاسخ باید مرز میان دانش رسمی، داده زنده، توضیح هوش مصنوعی و پیشنهاد را روشن نگه دارد.',
  'ریسک، شکل مرور، تأیید، احراز و توقف را تعیین می‌کند.',
  'یک هویت می‌تواند چند نقش و رابطه داشته باشد؛ زمینه فعال باید همیشه قابل فهم باشد.',
  'مسیر خدمت از آمادگی و ورود تا مرور، مرز تأیید و نتیجه با الگوهای مشترک ساخته می‌شود.',
  'ام‌بازار نمونه عمیق ترکیب کامپوننت، زمینه، سفارش، اقساط و توقف امن است.',
  'دوازده دامنه، یک زبان تجربه مشترک و هویت‌های خدمت قابل تشخیص دارند.',
  'تمام ۶۹ مسیر از رجیستری تایپ‌شده و شواهد ممیزی قابل ردیابی‌اند.',
  'مطالعه موردی نشان می‌دهد اجزا چگونه در مسئله واقعی محصول به یک مسیر منسجم تبدیل می‌شوند.',
  'تم و breakpoint ظاهر را تغییر می‌دهند، نه ترتیب معنا و اولویت اقدام را.',
  'دسترس‌پذیری یک الگوی پیاده‌سازی‌شده در ساختار، تعامل، متن و حرکت است.',
  'بارگذاری، خالی، خطا، درگاه و توقف امن بخشی از محصول‌اند؛ نه استثناهای پس از طراحی.',
  'موجودی تایپ‌شده، مرجع قطعی نام، هدف، گونه و حالت هر جزء است.',
  'معماری از foundation تا نمونه محصول، ردپای تصمیم طراحی را در کد حفظ می‌کند.',
  'هر تیم از یک مسیر مشترک استفاده می‌کند: توکن، جزء، ترکیب دامنه، ریسک و QA.',
  'قواعد خوب، کوتاه، قابل مشاهده و مستقیماً متصل به درس‌های پیاده‌سازی‌اند.',
] as const;

function page(sectionKey: string, sectionTitle: string, key: string, content: ReactNode, tone: FullPageSpec['tone'] = 'paper', className?: string): FullPageSpec {
  return { sectionKey, sectionTitle, key, content, tone, className };
}

function opener(index: number, tone: FullPageSpec['tone'] = 'ink'): FullPageSpec {
  const item = publicationSections[index - 1];
  return page(item[0], item[1], `${item[0]}-opener`, <SectionCover number={index} title={item[1]} english={item[2]} statement={sectionStatements[index - 1]} />, tone, 'catalog-book-chapter-opener');
}

function RuleGrid({ items, columns = 3 }: { items: Array<{ title: string; text: string; code?: string; tone?: string }>; columns?: 2 | 3 | 4 }) {
  return <div className={`catalog-book-rule-grid cols-${columns}`}>{items.map((item, index) => <article className={item.tone ? `tone-${item.tone}` : ''} key={`${item.title}-${index}`}><span>{(index + 1).toLocaleString('fa-IR')}</span><h3>{item.title}</h3>{item.code && <code dir="ltr">{item.code}</code>}<p>{item.text}</p></article>)}</div>;
}

function EditorialColumns({ children }: { children: ReactNode }) {
  return <div className="catalog-book-editorial-columns">{children}</div>;
}

function Bullets({ items }: { items: string[] }) {
  return <ul className="catalog-book-bullets">{items.map((item) => <li key={item}><i /><span>{item}</span></li>)}</ul>;
}

function MiniCode({ children }: { children: string }) {
  return <pre className="catalog-book-code" dir="ltr"><code>{children}</code></pre>;
}

function StatusStrip() {
  const statuses = [
    ['official', 'دانش رسمی', 'پاسخ مستند و پایدار'],
    ['live', 'داده زنده', 'وضعیت جاری سامانه'],
    ['ai', 'توضیح هوش مصنوعی', 'تفسیر قابل تمایز'],
    ['recommendation', 'پیشنهاد', 'اقدام بعدی غیرقطعی'],
  ];
  return <div className="catalog-book-trust-strip">{statuses.map(([key, title, text]) => <article className={`trust-${key}`} key={key}><i /><strong>{title}</strong><p>{text}</p><code dir="ltr">trust.{key}</code></article>)}</div>;
}

function IdentityGrid({ start, end }: { start: number; end: number }) {
  return <div className="catalog-book-identity-grid">{ecosystemIdentityServices.slice(start, end).map((service) => <article key={service.id}><MResalatServiceIcon service={service} size={64} /><div><strong>{service.titleFa}</strong><bdi dir="ltr">{service.titleEn}</bdi><span className={service.identity.source === 'official-asset' ? 'official' : 'designed'}>{service.identity.source === 'official-asset' ? 'دارایی رسمی' : 'طراحی MResalat System'}</span><small><bdi dir="ltr">{service.id}</bdi> · {service.source.type}</small></div></article>)}</div>;
}

function DomainPage({ domain, index }: { domain: (typeof exampleDomains)[number]; index: number }) {
  const routes = exampleRoutes.filter((route) => route.domain === domain.key);
  const services = routes.map((route) => serviceCatalog.find((item) => item.id === route.serviceId)!).filter(Boolean);
  const identity = ecosystemServiceById[domain.ecosystemServiceId];
  const risk = [...new Set(services.map((item) => item.riskLevel))].sort();
  const patterns = [...new Set(services.flatMap((item) => item.componentKeys.slice(-2)))].slice(0, 6);
  const screenshotByDomain: Record<string, string> = {
    membership: 'membership-domain', mhami: 'mhami-domain', mbazar: 'mbazar-home', learning: 'learning-domain', mhesam: 'mhesam-domain',
    'heavenly-resalat': 'heavenly-domain', msalamat: 'health-domain', mbime: 'insurance-domain', auxiliary: 'auxiliary-domain', rahyar: 'rahyar-domain', banking: 'banking-domain', communication: 'communication-domain',
  };
  return <div className="catalog-book-domain-page"><header><span>دامنه {(index + 1).toLocaleString('fa-IR')}</span><MResalatServiceIcon service={identity} size={64} /><div><h1>{domain.titleFa}</h1><bdi dir="ltr">{domain.titleEn}</bdi><p>{domain.description}</p></div></header><ScreenshotFigure src={`/catalog-book-generated/${screenshotByDomain[domain.key]}.png`} alt={`نمونه محصول ${domain.titleFa}`} number={`۱۵-${index + 1}`} title={`نمای پیاده‌سازی‌شده دامنه ${domain.titleFa}`} /><div className="catalog-book-domain-summary"><Stat value={routes.length} label="مسیر ممیزی‌شده" /><Stat value={risk.join(' / ')} label="سطوح ریسک" /><Stat value={identity.identity.source === 'official-asset' ? 'رسمی' : 'طراحی‌شده'} label="منبع هویت" /></div><div className="catalog-book-pattern-tags">{patterns.map((pattern) => <code dir="ltr" key={pattern}>{pattern}</code>)}</div></div>;
}

function RouteMatrixPage({ chapter }: { chapter: (typeof serviceCatalogChapters)[number] }) {
  const routes = serviceCatalog.filter((route) => route.chapter === chapter.id);
  return <div className="catalog-book-route-page"><PageTitle kicker={`۱۶ · فصل ${chapter.id.toLocaleString('fa-IR')}`} title={chapter.titleFa} english={chapter.titleEn} lead={`${routes.length.toLocaleString('fa-IR')} مسیر ممیزی‌شده این فصل با وضعیت شواهد، سطح ریسک، مرز توقف و الگوی اصلی ثبت شده‌اند.`} /><div className={`catalog-book-route-matrix dense rows-${routes.length}`}><div className="catalog-book-route-row is-head"><span>ش.</span><span>مسیر / route</span><span>وضعیت</span><span>ریسک</span><span>مرز توقف / الگوی اصلی</span></div>{routes.map((route, index) => <div className="catalog-book-route-row" key={route.id}><strong>{(index + 1).toLocaleString('fa-IR')}</strong><div><b>{route.titleFa}</b><bdi dir="ltr">{route.titleEn}</bdi><a href={route.demoHref} dir="ltr">{route.demoHref}</a></div><span>{route.verificationStatus}</span><RiskBadge level={route.riskLevel} /><div><p>{route.safeStopFa}</p><small dir="ltr">{route.surfaceKind} · {route.componentKeys.slice(-2).join(' + ')}</small></div></div>)}</div><footer className="catalog-book-route-proof"><span>منبع</span><bdi dir="ltr">example-route-registry.ts → service-catalog.ts</bdi><strong>{routes.length.toLocaleString('fa-IR')} / {routes.length.toLocaleString('fa-IR')}</strong></footer></div>;
}

const caseStudies = [
  [{ title: 'عضویت زیر ۱۸ سال', image: 'membership-under18', risk: 'L2', problem: 'هدایت سرپرست و نوجوان بدون دریافت داده واقعی', pattern: 'Stepper + Form + SafeReview', stop: 'پیش از احراز هویت و ثبت' }, { title: 'عضویت سازمانی', image: 'membership-organization', risk: 'L2', problem: 'مدیریت امضاداران و تمرکز بر اثر درخواست', pattern: 'Dialog + Signatory list + Review', stop: 'پیش از استعلام و ثبت' }],
  [{ title: 'وام بدون کارمزد', image: 'mhami-loan', risk: 'L3', problem: 'مرور درخواست حساس با مرز OTP روشن', pattern: 'Form + OTP boundary + ActionSummary', stop: 'پیش از تأیید OTP' }, { title: 'تسویه ام‌بازار', image: 'mbazar-checkout', risk: 'L3', problem: 'انتخاب تحویل و پرداخت بدون اجرای تراکنش', pattern: 'Stepper + Address + PaymentMode', stop: 'پیش از پرداخت' }],
  [{ title: 'تراکنش‌های ام‌حسام', image: 'mhesam-transactions', risk: 'L1', problem: 'مرور داده پوشانده با جستجو و فیلتر', pattern: 'Search + Filter + TransactionList', stop: 'فقط خواندنی' }, { title: 'برداشت اعتبار', image: 'mhesam-withdraw', risk: 'L3', problem: 'ورود مبلغ و مرور اثر پیش از اقدام', pattern: 'AmountPad + SafeReview', stop: 'پیش از انتقال' }],
  [{ title: 'اهدای اعتبار', image: 'mhesam-donate', risk: 'L3', problem: 'تمایز نیت خیرخواهانه از اثر مالی حساس', pattern: 'AmountPad + Recipient + Review', stop: 'پیش از تعهد مالی' }, { title: 'جستجوی ام‌آموزش', image: 'learning-provider', risk: 'L0', problem: 'کشف ارائه‌دهنده با اطلاعات عمومی', pattern: 'ProviderSearch + Filter + Preview', stop: 'پیش از رزرو/ورود' }],
  [{ title: 'نوبت‌های ام‌سلامت', image: 'health-appointments', risk: 'L1', problem: 'نمایش وضعیت بدون افشای پرونده سلامت', pattern: 'Tabs + AppointmentList + Empty', stop: 'فقط داده ساختگی' }, { title: 'بیمه شخص ثالث', image: 'insurance-vehicle', risk: 'L2', problem: 'جمع‌آوری حداقل داده برای مرور اولیه', pattern: 'VehicleInsuranceForm + Review', stop: 'پیش از قیمت‌گذاری' }],
  [{ title: 'فرم‌ساز سایا', image: 'auxiliary-saya', risk: 'L2', problem: 'معرفی توان فرم بدون جعل نتیجه ارزیابی', pattern: 'FormBuilderEntry + ActionSummary', stop: 'پیش از ذخیره' }, { title: 'درگاه ساتنا', image: 'banking-satna', risk: 'L3', problem: 'معرفی مقصد بانکی بدون تقلید اطلاعات ورود', pattern: 'ExternalProductGate + RiskNotice', stop: 'پیش از ورود بانکی' }],
  [{ title: 'ام‌پیام', image: 'communication-mpayam', risk: 'L1', problem: 'گفت‌وگوی ساختگی بدون پیام واقعی', pattern: 'ConversationList + Composer', stop: 'پیش از ارسال' }, { title: 'درگاه نقشه', image: 'communication-map', risk: 'L2', problem: 'توضیح نیاز به مکان بدون درخواست مختصات', pattern: 'PermissionGate + ActionSummary', stop: 'پیش از مجوز مکان' }],
] as const;

function CaseStudyPage({ pair, index }: { pair: (typeof caseStudies)[number]; index: number }) {
  return <div className="catalog-book-case-page"><PageTitle kicker={`۱۷ · مطالعه موردی ${index.toLocaleString('fa-IR')}`} title={`${pair[0].title} × ${pair[1].title}`} lead="دو مسئله متفاوت با الگوهای مشترک، سطح ریسک صریح و توقف امن قابل مشاهده." /><div className="catalog-book-case-grid">{pair.map((item, itemIndex) => <article key={item.title}><ScreenshotFigure src={`/catalog-book-generated/${item.image}.png`} alt={item.title} number={`۱۷-${index}-${itemIndex + 1}`} title={item.title} /><div className="catalog-book-case-meta"><RiskBadge level={item.risk} /><div><strong>مسئله</strong><p>{item.problem}</p></div><div><strong>الگوی طراحی</strong><code dir="ltr">{item.pattern}</code></div><div><strong>مرز توقف</strong><p>{item.stop}</p></div></div></article>)}</div></div>;
}

function InventoryPage({ items, index }: { items: typeof componentInventory; index: number }) {
  return <div className="catalog-book-inventory-page"><PageTitle kicker={`۲۱ · موجودی اجزا ${index.toLocaleString('fa-IR')}`} title={`${items[0].category} تا ${items.at(-1)?.category}`} lead="نام، هدف، گونه‌ها و حالت‌ها مستقیماً از موجودی تایپ‌شده خوانده شده‌اند." /><div className="catalog-book-inventory-table"><div className="is-head"><span>Component</span><span>هدف</span><span>گونه‌ها</span><span>حالت‌ها</span></div>{items.map((item) => <article key={item.name}><code dir="ltr">{item.name}</code><p>{item.purpose}</p><small dir="ltr">{item.variants.join(' · ')}</small><small dir="ltr">{item.states.join(' / ')}</small></article>)}</div><footer><span>ردیف‌های این صفحه</span><strong>{items.length.toLocaleString('fa-IR')}</strong><bdi dir="ltr">mresalat/core/component-inventory.ts</bdi></footer></div>;
}

function buildSectionPages(): FullPageSpec[] {
  const pages: FullPageSpec[] = [];
  const add = (spec: FullPageSpec) => pages.push(spec);

  add(opener(1));
  add(page('01', 'فلسفه و اصول سیستم طراحی', '01-principles', <><PageTitle kicker="۰۱ · اصول عملی" title="یازده اصل قابل مشاهده در کد" lead="این اصول از رفتار پیاده‌سازی‌شده، ساختار داده و سیاست‌های توقف استخراج شده‌اند؛ ادعای برند خارج از مخزن نیستند." /><RuleGrid items={[
    { title: 'فارسی‌محوری', text: 'متن، عدد و چیدمان از ابتدا برای زبان فارسی طراحی شده‌اند.' }, { title: 'RTL-first', text: 'ترتیب بصری و حرکت جهت‌دار با منطق راست‌به‌چپ هماهنگ است.' }, { title: 'خوانایی', text: 'اندازه، فاصله خط و عرض خواندن برای متن فارسی کنترل می‌شود.' }, { title: 'اعتماد', text: 'منبع، قطعیت و پیشنهاد از یکدیگر قابل تشخیص‌اند.' }, { title: 'طراحی برای فرایند', text: 'آمادگی، ورود، مرور و توقف به‌اندازه نتیجه اهمیت دارند.' }, { title: 'کنترل ریسک', text: 'سطح L0 تا L3 شکل تعامل و تأیید را تعیین می‌کند.' }, { title: 'زمینه کاربر', text: 'نقش، رابطه و سرویس مبدأ در تجربه حفظ می‌شود.' }, { title: 'استفاده مجدد', text: 'دامنه‌ها از اجزا و الگوهای مشترک ترکیب می‌شوند.' }, { title: 'پاسخ‌گویی', text: 'ترتیب معنا در موبایل، تبلت و دسکتاپ ثابت می‌ماند.' }, { title: 'دسترس‌پذیری', text: 'فوکوس، برچسب، کاهش حرکت و معنی غیررنگی پیاده‌سازی شده‌اند.' }, { title: 'روشن و تیره', text: 'توکن معنایی ثابت و مقدار زمینه‌محور است.' },
  ]} columns={3} /></>));
  add(page('01', 'فلسفه و اصول سیستم طراحی', '01-governance', <><PageTitle kicker="۰۱ · مدل بلوغ" title="کد، سند و QA یک چرخه‌اند" lead="موجودی تایپ‌شده، نمونه تعاملی و شواهد ممیزی در کنار هم از واگرایی طراحی و پیاده‌سازی جلوگیری می‌کنند." /><div className="catalog-book-process-diagram"><span>توکن و اصل</span><i>←</i><span>جزء مشترک</span><i>←</i><span>ترکیب دامنه</span><i>←</i><span>نمونه تعاملی</span><i>←</i><strong>QA و ممیزی</strong></div><EditorialColumns><div><h2>قانون پیاده‌سازی‌شده</h2><Bullets items={['رجیستری تایپ‌شده برای ۶۹ مسیر و ۹۶ جزء', 'تفکیک صریح شواهد از مجوز اقدام', 'fixture ساختگی و پوشانده برای داده حساس', 'توقف L2 و L3 پیش از اثر واقعی']} /></div><div><h2>شاخص‌های بلوغ</h2><div className="catalog-book-metric-wall"><Stat value={catalogBookFacts.components} label="جزء ثبت‌شده" /><Stat value={catalogBookFacts.routes} label="مسیر ممیزی‌شده" /><Stat value={catalogBookFacts.domains} label="دامنه محصول" /><Stat value={catalogBookFacts.identities} label="هویت خدمت" /></div></div></EditorialColumns><Callout title="مرز ادعا" tone="warning">این انتشار وجود الگوهای پیاده‌سازی‌شده را مستند می‌کند و ادعای گواهی رسمی WCAG، اتصال بانکی یا پوشش API تولید ندارد.</Callout></>));

  add(opener(2));
  add(page('02', 'هویت برند', '02-lockups', <><PageTitle kicker="۰۲ · دارایی رسمی" title="یک نشان، سه کاربرد" lead="فایل رسمی موجود در مخزن بدون بازسازی متنی یا نشانه جایگزین استفاده می‌شود." /><div className="catalog-book-logo-gallery"><article><BrandLockup /><strong>قفل کامل</strong><p>برای جلد، هدرهای رسمی و معرفی سیستم.</p></article><article className="dark"><BrandLockup inverted /><strong>سطح تیره</strong><p>دارایی روی زمینه کنترل‌شده روشن قرار می‌گیرد.</p></article><article><BrandLockup compact /><strong>کاربرد فشرده</strong><p>برای فضای محدود با حفظ خوانایی نشان.</p></article></div><Callout title="قانون پیاده‌سازی‌شده" tone="success">منبع دارایی: <Ltr>/public/brand/mresalat-logo.svg</Ltr>. نسبت، رنگ داخلی و ترکیب رسمی فایل تغییر نمی‌کند.</Callout><Callout title="راهنمای پیشنهادی" tone="info">فضای تنفس بصری حفظ شود؛ چون عدد رسمی clear-space در مخزن وجود ندارد، این انتشار قانون عددی تازه‌ای جعل نمی‌کند.</Callout></>));
  add(page('02', 'هویت برند', '02-brand-rules', <><PageTitle kicker="۰۲ · کاربرد صحیح" title="هویت را بازطراحی نکنید" lead="ثبات برند از استفاده درست دارایی رسمی و کنترل زمینه حاصل می‌شود." /><div className="catalog-book-do-dont"><section className="do"><h2>باید</h2><RuleGrid columns={2} items={[{ title: 'دارایی رسمی', text: 'فایل SVG موجود را بدون تغییر نسبت استفاده کنید.' }, { title: 'کنتراست زمینه', text: 'در سطح تیره، قاب روشن کنترل‌شده فراهم کنید.' }, { title: 'اندازه متناسب', text: 'گونه کامل و فشرده را متناسب با فضا انتخاب کنید.' }, { title: 'هویت خدمت', text: 'لوگوی خدمت را از لوگوی سیستم جدا نگه دارید.' }]} /></section><section className="dont"><h2>نباید</h2><RuleGrid columns={2} items={[{ title: 'کشش', text: 'نسبت دارایی را برای پر کردن فضا تغییر ندهید.' }, { title: 'بازرنگ‌آمیزی', text: 'رنگ‌های داخلی نشان را با رنگ صفحه جایگزین نکنید.' }, { title: 'نشان متنی', text: 'نام ام‌رسالت را به‌جای فایل رسمی تایپ نکنید.' }, { title: 'اثر تزئینی', text: 'سایه یا گرادیان تازه روی لوگو اضافه نکنید.' }]} /></section></div></>));

  add(opener(3));
  add(page('03', 'رنگ و توکن‌های معنایی', '03-token-table', <><PageTitle kicker="۰۳ · روشن و تیره" title="توکن معنایی، قرارداد پایدار" lead="نام برای مصرف‌کننده ثابت است و تم مقدار مناسب زمینه را تأمین می‌کند." /><div className="catalog-book-token-grid">{lightDarkTokens.slice(0, 8).map((token) => <TokenSwatch {...token} key={token.name} />)}</div><Callout title="منبع" tone="info"><Ltr>app/globals.css :root + html[data-theme=&apos;dark&apos;]</Ltr></Callout></>, 'soft'));
  add(page('03', 'رنگ و توکن‌های معنایی', '03-status-trust', <><PageTitle kicker="۰۳ · وضعیت و اعتماد" title="دو دستگاه معنایی مکمل" lead="وضعیت نتیجه تعامل را می‌گوید؛ trust منشأ یا نقش اطلاعات را روشن می‌کند." /><div className="catalog-book-token-grid compact">{[...lightDarkTokens.slice(8), ...trustTokens].map((token) => <TokenSwatch name={token.name} value={token.value} darkValue={'darkValue' in token ? token.darkValue : undefined} usage={token.usage} key={token.name} />)}</div><StatusStrip /><Callout title="اصل مشترک" tone="warning">رنگ هیچ‌گاه تنها حامل معنا نیست؛ برچسب فارسی، نماد و زمینه ساختاری همزمان استفاده می‌شوند.</Callout></>));
  add(page('03', 'رنگ و توکن‌های معنایی', '03-brand-ramp', <><PageTitle kicker="۰۳ · طیف برند" title="آبی غالب، فیروزه‌ای مکمل" lead="طیف موجود برای سطح، اقدام و نمودار کنترل‌شده استفاده می‌شود؛ نه برای تزئین بی‌هدف." /><div className="catalog-book-large-ramp">{brandTokens.map((token, index) => <article style={{ background: token.value, color: index < 3 ? '#103657' : '#fff' }} key={token.name}><code dir="ltr">{token.name}</code><bdi dir="ltr">{token.value}</bdi><p>{token.usage}</p></article>)}</div><RuleGrid columns={3} items={[{ title: 'سطح نرم', text: 'brand.50 و brand.100 برای زمینه و انتخاب کم‌تأکید.' }, { title: 'اطلاعات و نمودار', text: 'brand.300 و brand.500 برای نمایش داده کنترل‌شده.' }, { title: 'اقدام و تیتر', text: 'brand.700 و brand.900 برای اولویت و سطح تیره.' }]} /></>));

  add(opener(4));
  add(page('04', 'تایپوگرافی فارسی', '04-scale', <><PageTitle kicker="۰۴ · IRANSansX FaNum" title="سلسله‌مراتب برای خواندن، نه نمایش" lead="چهار وزن ۴۰۰، ۵۰۰، ۶۰۰ و ۷۰۰ از دارایی‌های محلی مخزن بارگذاری می‌شوند." /><div className="catalog-book-type-scale"><article className="display"><span>Display</span><h2>تجربه یکپارچه خدمات ام‌رسالت</h2><code dir="ltr">42px / 1.45 / 700</code></article><article className="page"><span>Page</span><h2>درخواست وام قرض‌الحسنه</h2><code dir="ltr">30–46px / 700</code></article><article className="section"><span>Section</span><h3>شرایط و مدارک مورد نیاز</h3><code dir="ltr">23–24px / 700</code></article><article className="card"><span>Card</span><h4>وضعیت درخواست نمونه</h4><code dir="ltr">17–19px / 600</code></article><article className="body"><span>Body</span><p>پیش از ادامه، اثر اقدام و مرز تأیید را مرور کنید.</p><code dir="ltr">14–15px / 1.85 / 400</code></article><article className="meta"><span>Meta</span><p>داده ساختگی · فقط نمایش</p><code dir="ltr">10–12px / 500</code></article></div></>));
  add(page('04', 'تایپوگرافی فارسی', '04-mixed-direction', <><PageTitle kicker="۰۴ · جداسازی جهت" title="فارسی، عدد و رشته فنی در یک سطر" lead="جزیره‌های LTR از ترتیب نشانه‌ها و خوانایی route، token و ID محافظت می‌کنند." /><div className="catalog-book-mixed-samples"><article><span>مبلغ</span><strong>۱۲٬۸۵۰٬۰۰۰ تومان</strong><small>عدد فارسی و واحد خوانا</small></article><article><span>تاریخ</span><strong>۱۴۰۵/۰۶/۰۶</strong><small>ترتیب ثابت رقم‌ها</small></article><article><span>شناسه</span><bdi dir="ltr">REQ-1405-0828-FA</bdi><small>جزیره LTR در متن RTL</small></article><article><span>توکن</span><bdi dir="ltr">surface.selected</bdi><small>نام فنی بدون جابه‌جایی نقطه</small></article><article className="wide"><span>مسیر</span><bdi dir="ltr">/examples/mhesam/credit/withdraw</bdi><small>مسیر فنی قابل کپی و جستجو</small></article></div><MiniCode>{`<p dir="rtl">\n  وضعیت مسیر <bdi dir="ltr">/examples/...</bdi> آماده مرور است.\n</p>`}</MiniCode><Callout title="قاعده" tone="success">برای route، token، ID و قطعه کد از <Ltr>dir=&quot;ltr&quot;</Ltr> یا <Ltr>&lt;bdi&gt;</Ltr> استفاده کنید؛ کل صفحه را برای حل یک رشته فنی LTR نکنید.</Callout></>));

  add(opener(5));
  add(page('05', 'شبکه، فاصله، گوشه و عمق', '05-grid', <><PageTitle kicker="۰۵ · شبکه پاسخ‌گو" title="۱۲ ستون تا ۴ ستون" lead="عرض محتوا تا ۱۱۸۰px محدود می‌شود و gutter صفحه در نمایش کوچک کاهش می‌یابد." /><Figure number="۵-۱" title="شبکه مرجع دسکتاپ، تبلت و موبایل"><div className="catalog-book-grid-diagram"><section className="desktop"><strong>Desktop</strong><div>{Array.from({ length: 12 }, (_, i) => <i key={i}>{i + 1}</i>)}</div><small>max content width · 1180px</small></section><section className="tablet"><strong>Tablet</strong><div>{Array.from({ length: 8 }, (_, i) => <i key={i}>{i + 1}</i>)}</div><small>ترکیب دو یا سه ستونه</small></section><section className="mobile"><strong>Mobile</strong><div>{Array.from({ length: 4 }, (_, i) => <i key={i}>{i + 1}</i>)}</div><small>ترتیب معنایی یک‌ستونه</small></section></div></Figure><Callout title="فلسفه breakpoint" tone="info">شکستن طرح بر اساس حفظ خوانایی، اندازه کنترل و ترتیب معنا انجام می‌شود؛ نه تقلید مکانیکی از عرض دستگاه.</Callout></>));
  add(page('05', 'شبکه، فاصله، گوشه و عمق', '05-spacing-radius-depth', <><PageTitle kicker="۰۵ · ریتم پایه ۴px" title="فاصله، گوشه و عمق کنترل‌شده" lead="توکن‌های محدود، ریتم بصری مشترک را در کارت، فرم و ناوبری حفظ می‌کنند." /><div className="catalog-book-foundation-board"><section><h2>فاصله</h2>{[4,8,12,16,20,24,32,40].map((value) => <div className="space" key={value}><i style={{ width: `${value * 2}px` }} /><code dir="ltr">space-${value / 4} · {value}px</code></div>)}</section><section><h2>گوشه</h2>{[['sm','10px'],['md','16px'],['lg','24px'],['pill','999px']].map(([name,value]) => <div className="radius" key={name}><i style={{ borderRadius: value }} /><code dir="ltr">radius-{name} · {value}</code></div>)}</section><section><h2>عمق</h2><div className="shadow sm">shadow-sm</div><div className="shadow md">shadow-md</div><p>عمق برای تفکیک سطح و تمرکز است؛ نه تزئین دائمی.</p></section></div></>));

  add(opener(6));
  add(page('06', 'آیکون‌نگاری و هویت خدمات', '06-icons', <><PageTitle kicker="۰۶ · MResalatIcon" title="آیکون عملکردی، معنای روشن" lead="مجموعه Lucide از wrapper تایپ‌شده عبور می‌کند تا نام، اندازه و رفتار جهت‌دار یکدست بماند." /><div className="catalog-book-icon-grid">{iconGalleryNames.slice(0, 36).map((name) => <article key={name}><MResalatIcon name={name} size={24} /><code dir="ltr">{name}</code></article>)}</div><div className="catalog-book-two-col"><Callout title="اندازه" tone="info">اندازه‌های ۱۶، ۲۰ و ۲۴ پیکسل برای متن، کنترل و کارت؛ اندازه بزرگ فقط برای نقش نمایشی.</Callout><Callout title="رفتار RTL" tone="success">`next` از ArrowLeft و `previous` از ArrowRight استفاده می‌کند تا حرکت با جریان فارسی هماهنگ باشد.</Callout></div></>));
  add(page('06', 'آیکون‌نگاری و هویت خدمات', '06-identities-a', <><PageTitle kicker="۰۶ · هویت خدمات ۱/۲" title="دارایی رسمی، در اولویت" lead="هر هویت با منبع خود نشان داده می‌شود؛ لوگو با آیکون عمومی جایگزین نمی‌شود." /><IdentityGrid start={0} end={9} /><Callout title="منبع هویت" tone="success">برچسب «دارایی رسمی» یعنی فایل موجود در <Ltr>public/service-identities</Ltr>؛ نه تأیید یا مالکیت تازه از سوی این انتشار.</Callout></>));
  add(page('06', 'آیکون‌نگاری و هویت خدمات', '06-identities-b', <><PageTitle kicker="۰۶ · هویت خدمات ۲/۲" title="fallback طراحی‌شده، صریح و قابل تشخیص" lead="برای گروه‌های بدون نشان رسمی مستقل، MResalat System هویت جایگزین طراحی‌شده را با وضعیت منبع شفاف ارائه می‌کند." /><IdentityGrid start={9} end={17} /><div className="catalog-book-size-strip">{[32,40,48,64].map((size) => <article key={size}><MResalatServiceIcon service={ecosystemServiceById.mbazar} size={size as 32|40|48|64} /><span>{size.toLocaleString('fa-IR')}px</span></article>)}</div><Callout title="قاعده" tone="warning">fallback طراحی‌شده هرگز به‌عنوان لوگوی رسمی محصول معرفی نمی‌شود.</Callout></>));

  add(opener(7));
  add(page('07', 'اجزای پایه', '07-actions-badges', <><PageTitle kicker="۰۷ · اقدام و وضعیت" title="Button و Badge" lead="سلسله‌مراتب اقدام و نمایش وضعیت باید در نخستین نگاه قابل تشخیص باشد." /><div className="catalog-book-component-board"><section><h2 dir="ltr">Button</h2><div className="catalog-book-button-demo"><button className="button button-primary">ادامه فرایند</button><button className="button button-secondary">مشاهده جزئیات</button><button className="button button-ghost">انصراف</button><button className="button button-danger">توقف اقدام</button><button className="button button-primary" disabled>غیرفعال</button></div><div className="catalog-book-anatomy"><span>۱. برچسب فعلی</span><span>۲. سطح تأکید</span><span>۳. وضعیت تعاملی</span></div></section><section><h2 dir="ltr">Badge</h2><div className="catalog-book-badge-demo"><span className="status-badge status-badge-info">اطلاعات</span><span className="status-badge status-badge-success">تأییدشده</span><span className="status-badge status-badge-warning">نیازمند بررسی</span><span className="status-badge status-badge-danger">توقف امن</span><span className="status-badge status-badge-warning status-badge-multiline">در انتظار تأیید سرپرست سازمان</span></div><div className="catalog-book-anatomy"><span>۱. intrinsic size</span><span>۲. عدم shrink</span><span>۳. شکست فقط بین واژه‌ها</span></div></section></div><Callout title="درس QA" tone="warning">Badge استاندارد `white-space: nowrap` دارد؛ گونه `multiline` فقط برای عبارت بلند و با `overflow-wrap: break-word` استفاده می‌شود.</Callout></>));
  add(page('07', 'اجزای پایه', '07-forms', <><PageTitle kicker="۰۷ · فرم فارسی" title="برچسب، راهنما، خطا و مرور" lead="فرم تنها مجموعه input نیست؛ ساختار توضیح و توقف آن بخشی از تجربه امن است." /><div className="catalog-book-form-demo"><label><span>نوع درخواست</span><select defaultValue=""><option value="" disabled>انتخاب کنید</option><option>درخواست نمونه</option></select><small>یکی از گزینه‌های موجود را انتخاب کنید.</small></label><label><span>شناسه پیگیری</span><input dir="ltr" placeholder="DEMO-0000" /><small>فقط مقدار ساختگی وارد کنید.</small></label><label className="error"><span>مبلغ</span><input inputMode="numeric" placeholder="۰" aria-invalid="true" /><small>مبلغ باید بیش از صفر باشد.</small></label><label><span>توضیح</span><textarea placeholder="توضیح کوتاه و غیرحساس" /><small>اطلاعات شخصی یا مالی واقعی ننویسید.</small></label></div><div className="catalog-book-form-flow"><span>آمادگی</span><i>←</i><span>ورود</span><i>←</i><span>اعتبارسنجی محلی</span><i>←</i><strong>مرور امن</strong><i>←</i><em>ارسال غیرفعال</em></div><Callout title="دسترس‌پذیری" tone="success">برچسب programmatic، متن کمک، `aria-invalid`، پیام خطای خوانا و ترتیب منطقی فوکوس باید همزمان وجود داشته باشند.</Callout></>));
  add(page('07', 'اجزای پایه', '07-feedback', <><PageTitle kicker="۰۷ · بازخورد" title="Alert، loading و نتیجه" lead="بازخورد باید هم وضعیت را نام‌گذاری کند و هم اقدام بعدی را توضیح دهد." /><div className="catalog-book-alert-stack"><article className="info"><MResalatIcon name="help" size={22} /><div><strong>اطلاعات</strong><p>این مسیر فقط راهنمای عمومی را نشان می‌دهد.</p></div></article><article className="success"><MResalatIcon name="success" size={22} /><div><strong>موفق</strong><p>مرحله نمایشی تکمیل شد؛ هیچ داده‌ای ارسال نشده است.</p></div></article><article className="warning"><MResalatIcon name="warning" size={22} /><div><strong>نیازمند توجه</strong><p>پیش از ادامه، اثر اقدام را مرور کنید.</p></div></article><article className="danger"><MResalatIcon name="error" size={22} /><div><strong>توقف امن</strong><p>اجرای واقعی این اقدام در نسخه نمایشی غیرفعال است.</p></div></article></div><div className="catalog-book-loading-demo"><div><i /><i /><i /></div><span>بارگذاری</span><p>اسکلت باید ساختار نهایی را تقریب بزند و از جهش شدید صفحه جلوگیری کند.</p></div></>));
  add(page('07', 'اجزای پایه', '07-discovery', <><PageTitle kicker="۰۷ · کشف" title="Search، filter، tabs و chips" lead="اجزای کشف برای مرور محلی داده ساختگی و حفظ وضعیت انتخاب طراحی شده‌اند." /><div className="catalog-book-discovery-demo"><div className="search"><MResalatIcon name="search" size={20} /><span>نام خدمت یا اقدام را جستجو کنید…</span></div><div className="filters"><button className="active">همه</button><button>عضویت</button><button>اعتبار و اقساط</button><button>ام‌بازار</button><button>بانکداری</button></div><div className="tabs" role="tablist"><button role="tab" aria-selected="true">فعال</button><button role="tab" aria-selected="false">تکمیل‌شده</button><button role="tab" aria-selected="false">نیازمند اقدام</button></div><div className="chips"><span>ریسک L2</span><span>توقف امن</span><span>فقط ساختگی</span><span>پاک‌کردن ×</span></div></div><RuleGrid columns={3} items={[{ title: 'جستجوی محلی', text: 'ورودی با label و حالت بدون نتیجه.' }, { title: 'فیلتر قابل پاک‌شدن', text: 'انتخاب فعلی و تعداد نتیجه همزمان دیده می‌شود.' }, { title: 'تب معنایی', text: 'role و aria-selected با محتوای قابل مشاهده هماهنگ‌اند.' }]} /></>));
  add(page('07', 'اجزای پایه', '07-empty-unavailable', <><PageTitle kicker="۰۷ · حالت‌های مرزی" title="خالی، درگاه، ناموجود" lead="نبود داده با نبود قابلیت یکسان نیست؛ هر وضعیت زبان و اقدام بازیابی متفاوت دارد." /><div className="catalog-book-state-cards"><article><MResalatIcon name="search" size={28} /><h2>نتیجه‌ای پیدا نشد</h2><p>فیلتر را پاک کنید یا عبارت دیگری بنویسید.</p><button className="button button-secondary">پاک‌کردن فیلترها</button></article><article><MResalatIcon name="lock" size={28} /><h2>ورود در سامانه مستقل</h2><p>این دمو اطلاعات ورود دریافت نمی‌کند.</p><button className="button button-primary" disabled>ورود غیرفعال</button></article><article><MResalatIcon name="error" size={28} /><h2>خدمت در دسترس نیست</h2><p>وضعیت ممیزی ثبت شده و گردش‌کار جایگزین جعل نشده است.</p><button className="button button-ghost">بازگشت</button></article></div><Callout title="اصل صداقت" tone="danger">`unavailable`، `not-visible` و `gated` را با فرم یا محتوای ساختگی پر نکنید.</Callout></>));

  add(opener(8));
  add(page('08', 'ناوبری و پوسته محصول', '08-app-shell', <><PageTitle kicker="۰۸ · AppShell" title="زمینه ثابت برای حرکت میان دامنه‌ها" lead="هدر، ناوبری اصلی، کنترل تم، حساب و ناوبری موبایل در پوسته مشترک ترکیب می‌شوند." /><ScreenshotFigure src="/catalog-book-generated/home-light.png" alt="پوسته اصلی ام‌رسالت" number="۸-۱" title="AppShell در خانه عمومی" /><div className="catalog-book-anatomy horizontal"><span>۱. هویت سیستم</span><span>۲. ناوبری اصلی</span><span>۳. کنترل تم</span><span>۴. زمینه حساب</span><span>۵. نوار موبایل</span></div></>));
  add(page('08', 'ناوبری و پوسته محصول', '08-context-navigation', <><PageTitle kicker="۰۸ · ناوبری در زمینه" title="breadcrumb، domain strip و mobile nav" lead="هر سطح جهت بازگشت، دامنه فعلی و مسیرهای هم‌خانواده را بدون ازدحام نشان می‌دهد." /><div className="catalog-book-nav-examples"><section><span>مسیر صفحه</span><nav>نمونه‌های محصول <i>←</i> ام‌حسام <i>←</i> <strong>برداشت اعتبار</strong></nav></section><section><span>مسیرهای دامنه</span><nav className="pills"><b>تراکنش‌ها</b><b>اعتبار ام‌حسام</b><b className="active">برداشت اعتبار</b><b>MQR</b></nav></section><section className="mobile"><span>موبایل</span><nav><b>خانه</b><b>تجربه‌ها</b><b className="active">نمونه‌ها</b><b>دستیار</b><b>MResalat</b></nav></section></div><Callout title="رفتار responsive" tone="info">در موبایل، ناوبری افقی دامنه می‌تواند scroll شود؛ محتوای اصلی نباید برای جا دادن همه برچسب‌ها کوچک شود.</Callout></>));

  add(opener(9, 'cyan'));
  add(page('09', 'دستیار هوشمند ام‌رسالت', '09-character', <><PageTitle kicker="۰۹ · SmartAssistant3D" title="بدن کامل و پرتره از یک rig" lead="شخصیت procedural با pivotهای قابل بازرسی ساخته شده و برای حالت‌های مختلف geometry تازه mount نمی‌کند." /><ScreenshotFigure src="/catalog-book-generated/mascot-happy.png" alt="دستیار هوشمند ام‌رسالت" number="۹-۱" title="حالت happy در سطح کامل و پرتره" fit="contain" /><div className="catalog-book-metric-wall four"><Stat value={10} label="emotion" /><Stat value={9} label="hand pose" /><Stat value={2} label="mode" /><Stat value={1} label="Canvas مرجع" /></div></>, 'cyan'));
  add(page('09', 'دستیار هوشمند ام‌رسالت', '09-states', <><PageTitle kicker="۰۹ · نگاشت حالت" title="از وضعیت محصول تا رفتار شخصیت" lead="حالت چهره و ژست، بازتاب وضعیت فرایند است و نباید مستقل از محتوای HTML تصمیم‌گیری شود." /><div className="catalog-book-dual-figure"><ScreenshotFigure src="/catalog-book-generated/mascot-thinking.png" alt="حالت در حال فکر" number="۹-۲" title="thinking · در حال پردازش" fit="contain" /><ScreenshotFigure src="/catalog-book-generated/mascot-warning.png" alt="حالت هشدار" number="۹-۳" title="warning · اقدام حساس" fit="contain" /></div><div className="catalog-book-state-map">{[['focus','listening'],['submit','thinking'],['answer','explaining'],['success','happy'],['unknown','uncertain'],['security','warning'],['support','handoff']].map(([product,mascot]) => <span key={product}><code dir="ltr">{product}</code><i>←</i><code dir="ltr">{mascot}</code></span>)}</div></>));
  add(page('09', 'دستیار هوشمند ام‌رسالت', '09-motion-gaze', <><PageTitle kicker="۰۹ · حرکت و نگاه" title="کنترل‌شده، زمینه‌مند و قابل توقف" lead="یک سیستم انیمیشن با مقیاس دامنه، به‌جای چند پیاده‌سازی جداگانه استفاده می‌شود." /><RuleGrid columns={3} items={[{ title: 'شدت حرکت', code: 'restrained / normal / expressive', text: 'دامنه حرکت تغییر می‌کند؛ معنا و rig ثابت است.' }, { title: 'نگاه', code: 'none / local / page', text: 'نگاه می‌تواند خاموش، محدود به قاب یا وابسته به صفحه باشد.' }, { title: 'سلام یک‌باره', code: '2.7s', text: 'آمادگی، بالا آوردن دست، اوج موج، پایین آمدن و بازگشت.' }, { title: 'کاهش حرکت', code: 'prefers-reduced-motion', text: 'حرکت پیوسته و gaze ثبت نمی‌شوند؛ pose پایدار باقی می‌ماند.' }, { title: 'خارج از دید', code: 'IntersectionObserver', text: 'کار pointer و animation متوقف می‌شود.' }, { title: 'بازپخش کنترل‌شده', code: 'animationKey', text: 'فقط سلام جاری را بدون remount صحنه تکرار می‌کند.' }]} /><MiniCode>{`<SmartAssistant3D\n  mode="complete"\n  emotion="greeting"\n  motionIntensity="normal"\n  gaze="page"\n  transparent\n/>`}</MiniCode></>));
  add(page('09', 'دستیار هوشمند ام‌رسالت', '09-fallback-policy', <><PageTitle kicker="۰۹ · عملکرد و fallback" title="راهنما می‌ماند، حتی بدون WebGL" lead="Canvas یک enhancement است؛ ساختار محصول و پاسخ اصلی هرگز به آن وابسته نیست." /><div className="catalog-book-resource-policy"><section><h2>سیاست WebGL</h2><Bullets items={['تشخیص پشتیبانی یک‌بار در session', 'DPR بین ۱ و ۱٫۵', 'بدون shadow، bloom و post-processing', 'material مشترک و dispose در unmount', 'یک Canvas زنده در Showcase']} /></section><section><h2>fallback ایستا</h2><Bullets items={['Avatar در اندازه ۳۲ تا ۹۶px با CSS', 'حفظ silhouette، صورت و رنگ‌های کلیدی', 'نمایش حالت قابل تشخیص', 'عدم تخصیص renderer دوم', 'فعال ماندن تمام کنترل‌های HTML']} /></section></div><Callout title="قابلیت دسترسی" tone="success">Canvas از فناوری کمکی پنهان است؛ outer component برچسب تصویری کوتاه دارد و تمام پاسخ‌ها، کنترل‌ها و وضعیت‌ها در HTML باقی می‌مانند.</Callout></>));

  add(opener(10));
  add(page('10', 'اعتماد، RAG و پاسخ مستند', '10-trust-model', <><PageTitle kicker="۱۰ · TrustLegend" title="چهار نقش اطلاعات" lead="کاربر باید بداند یک گزاره از دانش رسمی، داده زنده، توضیح AI یا پیشنهاد آمده است." /><StatusStrip /><div className="catalog-book-trust-example"><header><span className="trust-official">دانش رسمی</span><strong>شرایط عضویت</strong></header><p>مراحل و مدارک بر اساس منبع رسمی معرفی می‌شوند.</p><footer><span className="trust-ai">توضیح هوش مصنوعی</span><p>این جمع‌بندی برای ساده‌سازی خواندن تولید شده است.</p></footer></div><Callout title="شفافیت منبع" tone="info">`SourceCitation` در مجاورت پاسخ قرار می‌گیرد؛ منبع در پانویس دور از ادعا پنهان نمی‌شود.</Callout></>));
  add(page('10', 'اعتماد، RAG و پاسخ مستند', '10-uncertain-handoff', <><PageTitle kicker="۱۰ · قطعیت و ارجاع" title="نمی‌دانم، یک حالت معتبر است" lead="پاسخ نامطمئن باید محدودیت را توضیح دهد و مسیر انسانی یا منبع جایگزین ارائه کند." /><div className="catalog-book-answer-states"><article><MResalatIcon name="evidence" size={28} /><h2 dir="ltr">SourceCitation</h2><p>عنوان، سازمان، زمان و نوع منبع را به پاسخ متصل می‌کند.</p><span>منبع رسمی ام‌رسالت · بازبینی‌شده</span></article><article><MResalatIcon name="help" size={28} /><h2 dir="ltr">UncertainAnswer</h2><p>به‌جای حدس، محدوده دانسته‌ها و دلیل نبود پاسخ را روشن می‌کند.</p><span>اطلاعات کافی برای پاسخ قطعی ندارم.</span></article><article><MResalatIcon name="support" size={28} /><h2 dir="ltr">HumanHandoff</h2><p>زمینه گفت‌وگو را بدون افشای داده حساس برای ادامه انسانی آماده می‌کند.</p><span>ادامه با پشتیبان</span></article></div><MiniCode>{`<SourceCitation source={officialSource} />\n<UncertainAnswer />\n<HumanHandoff />`}</MiniCode></>));

  add(opener(11));
  add(page('11', 'ریسک و اقدامات حساس', '11-risk-matrix', <><PageTitle kicker="۱۱ · مدل L0–L3" title="ریسک، معماری تعامل را تعیین می‌کند" lead="هر سطح، نوع داده، مرور و کنترل لازم را مشخص می‌کند." /><div className="catalog-book-risk-matrix">{[
    ['L0','دانش عمومی','اطلاع و کشف','بدون ورود یا ارسال'],['L1','مشاهده احراز‌شده','داده پوشانده و فقط خواندنی','بدون تغییر رکورد'],['L2','اقدام کنترل‌شده','مرور، رضایت و قابلیت بازگشت','پیش از ذخیره یا ارسال'],['L3','اقدام حساس','تأیید صریح و احراز قوی','پیش از اثر واقعی'],
  ].map(([level,title,pattern,stop]) => <article key={level}><RiskBadge level={level as 'L0'|'L1'|'L2'|'L3'} /><div><h2>{title}</h2><p>{pattern}</p><strong>{stop}</strong></div></article>)}</div><Callout title="توزیع واقعی رجیستری" tone="info">L0: ۱۲ مسیر · L1: ۱۸ مسیر · L2: ۲۱ مسیر · L3: ۱۸ مسیر</Callout></>));
  add(page('11', 'ریسک و اقدامات حساس', '11-secure-flow', <><PageTitle kicker="۱۱ · SecureActionFlow" title="اطلاع تا رسید، با مرز اجرای روشن" lead="اقدام حساس به چند گام کوچک و قابل توقف تقسیم می‌شود." /><div className="catalog-book-secure-flow"><span><b>۱</b>اطلاع<small>اثر و ریسک</small></span><i>←</i><span><b>۲</b>مرور<small>مقدار و مقصد</small></span><i>←</i><span><b>۳</b>تأیید<small>رضایت صریح</small></span><i>←</i><span><b>۴</b>احراز قوی<small>OTP / step-up</small></span><i>←</i><strong>مرز اجرا</strong></div><div className="catalog-book-secure-panels"><article><h2>نقطه توقف امن</h2><p>دموی کاتالوگ پیش از اثر واقعی متوقف می‌شود و این مرز را در متن و کنترل نشان می‌دهد.</p></article><article><h2>رسید نمایشی</h2><p>رسید فقط نتیجه local را شرح می‌دهد و شناسه تولید، انتقال یا تعهد واقعی نمی‌سازد.</p></article></div><Callout title="سیاست محصول" tone="danger">هیچ صفحه نمونه در این مخزن عملیات مالی، بیمه‌ای، پزشکی یا بانکی واقعی انجام نمی‌دهد.</Callout></>));
  add(page('11', 'ریسک و اقدامات حساس', '11-otp-permission', <><PageTitle kicker="۱۱ · احراز و مجوز" title="OTP، PermissionState و ApprovalRequest" lead="کنترل حساس باید دلیل، اثر و مرجع تصمیم را قابل فهم کند." /><div className="catalog-book-security-patterns"><section><h2 dir="ltr">OtpInput</h2><div className="otp" dir="ltr">{Array.from({ length: 6 }, (_, i) => <i key={i}>{i < 2 ? '•' : ''}</i>)}</div><p>در نمونه، کد واقعی دریافت یا اعتبارسنجی نمی‌شود.</p></section><section><h2 dir="ltr">PermissionState</h2><span className="permission">نیازمند تأیید والد</span><p>امکان مشاهده یا اقدام پیش از تعامل نام‌گذاری می‌شود.</p></section><section><h2 dir="ltr">ApprovalRequestCard</h2><strong>درخواست افزایش حد نمونه</strong><p>منبع، اثر و فرد تأییدکننده پیش از تصمیم نمایش داده می‌شوند.</p></section></div><RuleGrid columns={3} items={[{ title: 'قابل بازگشت', text: 'کاربر پیش از تأیید بتواند به مرور برگردد.' }, { title: 'بدون غافلگیری', text: 'اثر و مقصد در مرحله نهایی دوباره نمایش داده شوند.' }, { title: 'توقف معنادار', text: 'دکمه غیرفعال، دلیل و مسیر بعدی روشن داشته باشد.' }]} /></>));

  add(opener(12));
  add(page('12', 'سگمنت، زمینه و رابطه', '12-segments', <><PageTitle kicker="۱۲ · ده تجربه مخاطب" title="یک سیستم، زمینه‌های متفاوت" lead="سگمنت لحن، اولویت و مسیر را تغییر می‌دهد؛ foundation و مدل ریسک مشترک باقی می‌مانند." /><div className="catalog-book-segment-grid">{segments.map((segment) => <article key={segment.id}><MResalatIcon name={segment.icon} size={22} /><div><strong>{segment.name}</strong><code dir="ltr">{segment.slug}</code><p>{segment.description}</p></div><span>{segment.mode}</span></article>)}</div></>));
  add(page('12', 'سگمنت، زمینه و رابطه', '12-context-switcher', <><PageTitle kicker="۱۲ · UserContextSwitcher" title="نقش فعال همیشه دیده می‌شود" lead="یک هویت می‌تواند عضو، والد، کارمند یا مدیر باشد؛ تغییر نقش نباید زمینه را پنهان کند." /><div className="catalog-book-context-demo"><header><span className="mock-avatar">م</span><div><strong>حساب نمایشی</strong><small>زمینه فعال: والد</small></div><MResalatIcon name="down" size={18} /></header><div><button className="active"><MResalatIcon name="parent" size={20} />والد<small>آریا و سارا</small></button><button><MResalatIcon name="profile" size={20} />عضو شخصی<small>خدمات عمومی</small></button><button><MResalatIcon name="employee" size={20} />کارمند سازمان<small>برنامه مزایا</small></button></div></div><Callout title="بازگردانی" tone="info">زمینه انتخاب‌شده باید پس از بازگشت صفحه قابل بازیابی باشد؛ اگر دسترسی تغییر کرده، دلیل بازنشانی روشن نمایش داده شود.</Callout></>));
  add(page('12', 'سگمنت، زمینه و رابطه', '12-relationship', <><PageTitle kicker="۱۲ · رابطه و مجوز" title="والد، نوجوان، مدیر و پرسنل" lead="رابطه، سطح دسترسی و نیاز به تأیید را تعیین می‌کند؛ نه صرفاً سبک ظاهری را." /><div className="catalog-book-relationship-map"><article><MResalatIcon name="parent" size={28} /><h2>والد</h2><p>انتخاب فرزند، مرور درخواست و تأیید کنترل‌شده.</p><span>ChildSelector</span></article><i>↔</i><article><MResalatIcon name="child" size={28} /><h2>نوجوان</h2><p>هدف، پاداش و درخواست با زبان روشن درباره همراهی والد.</p><span>PermissionState</span></article><article><MResalatIcon name="organization" size={28} /><h2>مدیر سازمان</h2><p>برنامه، پرسنل، تخصیص اعتبار و وضعیت تأیید.</p><span>ApprovalRequestCard</span></article><i>↔</i><article><MResalatIcon name="employee" size={28} /><h2>پرسنل</h2><p>مزایا، باقی‌مانده و مقصد خرید در زمینه سازمان.</p><span>CrossServiceContextMarker</span></article></div></>));
  add(page('12', 'سگمنت، زمینه و رابطه', '12-segment-components', <><PageTitle kicker="۱۲ · اجزای زمینه" title="اولویت، مسیر و اقدام بعدی" lead="اجزای مشترک، تفاوت زمینه را بدون تکثیر معماری منتقل می‌کنند." /><RuleGrid columns={3} items={[
    { title: 'SegmentHero', code: 'mode + tone', text: 'معرفی نیاز و اولویت اصلی مخاطب.' }, { title: 'SegmentActionCard', code: 'primary / secondary', text: 'اقدام زمینه‌مند با توضیح اثر.' }, { title: 'SegmentStatusPanel', code: 'info / warning / success', text: 'خلاصه وضعیت مرتبط با سگمنت.' }, { title: 'ActiveJourneyCard', code: 'compact / full', text: 'مرحله فعلی، پیشرفت و اقدام بعدی.' }, { title: 'NextBestAction', code: 'approval / expiry / journey', text: 'اولویت قابل توضیح برای زمینه فعال.' }, { title: 'SegmentAIEntry', code: 'prompts + source', text: 'پرسش‌های نمونه و پاسخ مبتنی بر زمینه.' },
  ]} /><div className="catalog-book-process-diagram"><span>زمینه فعال</span><i>←</i><span>اولویت</span><i>←</i><span>مسیر جاری</span><i>←</i><strong>اقدام بعدی</strong></div></>));

  add(opener(13));
  add(page('13', 'الگوهای مسیر خدمت', '13-template', <><PageTitle kicker="۱۳ · ServicePageTemplate" title="قاب مشترک، محتوای دامنه‌ای" lead="breadcrumb، hero، منبع، benefit، journey، FAQ و دستیار در یک پوسته قابل ترکیب قرار می‌گیرند." /><div className="catalog-book-template-wire"><header>Breadcrumb</header><section><div>Hero copy<br/><small>عنوان · توضیح · اقدام</small></div><aside>Service visual</aside></section><main><div>Benefits · Requirements · Journey · FAQ</div><aside>Assistant + CTA</aside></main></div><Callout title="اصل ترکیب" tone="success">Template ساختار را ثابت می‌کند؛ متن، هویت، ریسک و اجزای دامنه از پیکربندی و ترکیب مشخص می‌آیند.</Callout></>));
  add(page('13', 'الگوهای مسیر خدمت', '13-wizard', <><PageTitle kicker="۱۳ · ProcessReviewWizard" title="فرایند چندگامی با مرور صریح" lead="مرحله جاری، کامل‌شده و آینده با متن و ساختار از یکدیگر تفکیک می‌شوند." /><div className="catalog-book-wizard"><ol>{['آمادگی','ورود اطلاعات','بررسی محلی','مرور اثر','مرز تأیید'].map((step,index) => <li className={index < 2 ? 'done' : index === 2 ? 'current' : ''} key={step}><span>{(index+1).toLocaleString('fa-IR')}</span><strong>{step}</strong></li>)}</ol><section><span>مرحله ۳ از ۵</span><h2>بررسی محلی اطلاعات</h2><p>مقادیر ساختگی برای خطاهای قالب، تکمیل بودن و توضیح اثر بررسی می‌شوند.</p><div><button className="button button-secondary">بازگشت</button><button className="button button-primary">مرور بعدی</button></div></section></div><Callout title="مرز بازبینی" tone="warning">رفتن به مرحله بعد معادل ارسال، ذخیره یا اجرای اقدام نیست؛ دکمه و متن باید این تفاوت را روشن کنند.</Callout></>));
  add(page('13', 'الگوهای مسیر خدمت', '13-examples', <><PageTitle kicker="۱۳ · ترکیب‌های واقعی" title="عضویت، ام‌حسام و بانکداری" lead="سه دامنه، یک دستور زبان فرایند و سه سطح متفاوت ریسک." /><div className="catalog-book-journey-comparison"><article><h2>عضویت</h2><RiskBadge level="L2" /><p>شرایط ← اطلاعات ← امضادار/سرپرست ← مرور ← توقف</p><code dir="ltr">Form + Dialog + SafeReview</code></article><article><h2>ام‌حسام</h2><RiskBadge level="L3" /><p>مبلغ ← مقصد ← اثر ← تأیید ← توقف پیش از انتقال</p><code dir="ltr">AmountPad + ActionSummary</code></article><article><h2>بانکداری</h2><RiskBadge level="L3" /><p>راهنما ← درگاه مستقل ← عدم دریافت credential</p><code dir="ltr">ExternalProductGate</code></article></div><ScreenshotFigure src="/catalog-book-generated/mhesam-withdraw.png" alt="مسیر برداشت اعتبار" number="۱۳-۱" title="نمونه ترکیب فرم، مرحله و مرور در ام‌حسام" /></>));

  add(opener(14, 'cyan'));
  add(page('14', 'ام‌بازار', '14-ecosystem', <><PageTitle kicker="۱۴ · دامنه مرجع" title="از کشف تا خدمات پس از خرید" lead="ام‌بازار خانواده‌ای از ۲۶ جزء ثبت‌شده را در چند مسیر پیوسته ترکیب می‌کند." /><ScreenshotFigure src="/catalog-book-generated/mbazar-home.png" alt="خانه ام‌بازار" number="۱۴-۱" title="خانه و کشف کالای ام‌بازار" /><div className="catalog-book-process-diagram"><span>کشف</span><i>←</i><span>محصول</span><i>←</i><span>سبد</span><i>←</i><span>تسویه</span><i>←</i><span>سفارش</span><i>←</i><strong>پشتیبانی</strong></div></>, 'cyan'));
  const marketItems = componentInventory.filter((item) => item.category === 'Marketplace');
  add(page('14', 'ام‌بازار', '14-components-a', <><PageTitle kicker="۱۴ · اجزای کشف و خرید" title="کالا، قیمت، فیلتر و پیش‌نمایش" lead="جزء به‌جای صفحه یک‌بارمصرف، نقش مشخص در چند مسیر دارد." /><RuleGrid columns={3} items={marketItems.slice(0, 12).map((item) => ({ title: item.name, code: item.variants.slice(0,2).join(' / '), text: item.purpose }))} /></>));
  add(page('14', 'ام‌بازار', '14-components-b', <><PageTitle kicker="۱۴ · اجزای سفارش و حساب" title="اقساط، مرسوله، علاقه‌مندی و پشتیبانی" lead="حالت و اقدام بعدی، اولویت اصلی اجزای پس از خرید هستند." /><RuleGrid columns={3} items={marketItems.slice(12).map((item) => ({ title: item.name, code: item.states.slice(0,2).join(' / '), text: item.purpose }))} /></>));
  add(page('14', 'ام‌بازار', '14-discovery', <><PageTitle kicker="۱۴ · جریان کشف" title="جستجو، دسته و محصول" lead="کشف نیازمحور از جستجوی متنی تا مرور کارت و quick view ادامه می‌یابد." /><div className="catalog-book-dual-figure"><ScreenshotFigure src="/catalog-book-generated/mbazar-search.png" alt="جستجوی ام‌بازار" number="۱۴-۲" title="جستجو و فیلتر" /><ScreenshotFigure src="/catalog-book-generated/mbazar-home.png" alt="کارت‌های کالا" number="۱۴-۳" title="دسته و پیشنهاد" /></div><div className="catalog-book-flow-line light"><span>MBazarSearch</span><i>←</i><span>MBazarFilterBar</span><i>←</i><span>MBazarProductCard</span><i>←</i><strong>QuickView</strong></div></>));
  add(page('14', 'ام‌بازار', '14-cart-checkout', <><PageTitle kicker="۱۴ · خرید" title="سبد تا مرز پرداخت" lead="تعداد، فروشنده، ارسال، روش پرداخت و مرور نهایی در چند گام خوانا تفکیک می‌شوند." /><div className="catalog-book-dual-figure"><ScreenshotFigure src="/catalog-book-generated/mbazar-cart.png" alt="سبد ام‌بازار" number="۱۴-۴" title="سبد و خلاصه خرید" /><ScreenshotFigure src="/catalog-book-generated/mbazar-checkout.png" alt="تسویه ام‌بازار" number="۱۴-۵" title="تحویل و روش پرداخت" /></div><Callout title="L3 · مرز پرداخت" tone="danger">هیچ مبلغ، سفارش یا تعهد مالی اجرا نمی‌شود؛ button نهایی اثر را شرح می‌دهد و غیرفعال باقی می‌ماند.</Callout></>));
  add(page('14', 'ام‌بازار', '14-installments', <><PageTitle kicker="۱۴ · خرید اقساطی" title="شرایط، طرح و درخواست" lead="نتیجه سیستم از توضیح هوش مصنوعی جدا می‌ماند و طرح‌ها مقایسه‌پذیرند." /><ScreenshotFigure src="/catalog-book-generated/mbazar-installments.png" alt="مرکز اقساط ام‌بازار" number="۱۴-۶" title="مرکز درخواست‌های اقساطی" /><div className="catalog-book-process-diagram"><span>شرایط</span><i>←</i><span>نتیجه سیستم</span><i>←</i><span>توضیح AI</span><i>←</i><span>انتخاب طرح</span><i>←</i><strong>درخواست نمایشی</strong></div><Callout title="تفکیک منبع" tone="ai">`InstallmentEligibilityPanel` نتیجه قطعی mock system را جدا از توضیح AI نمایش می‌دهد.</Callout></>));
  add(page('14', 'ام‌بازار', '14-orders', <><PageTitle kicker="۱۴ · پس از خرید" title="سفارش، مرسوله و اقدام بعدی" lead="وضعیت فعلی به زبان خریدار ترجمه و پیشرفت هر فروشنده مستقل نمایش داده می‌شود." /><ScreenshotFigure src="/catalog-book-generated/mbazar-orders.png" alt="سفارش‌های ام‌بازار" number="۱۴-۷" title="سفارش‌ها و وضعیت‌های چندگانه" /><RuleGrid columns={4} items={[{ title: 'فعال', text: 'آماده‌سازی و اقدام بعدی.' },{ title: 'تحویل‌شده', text: 'رسید و امکان نظر.' },{ title: 'لغوشده', text: 'دلیل و نتیجه بدون ابهام.' },{ title: 'دارای مسئله', text: 'ورود مستقیم به پشتیبانی.' }]} /></>));

  add(opener(15));
  exampleDomains.forEach((domain, index) => add(page('15', '۱۲ دامنه خدمات ام‌رسالت', `15-domain-${domain.key}`, <DomainPage domain={domain} index={index} />, index % 4 === 2 ? 'soft' : 'paper')));

  add(opener(16));
  serviceCatalogChapters.forEach((chapter) => add(page('16', '۶۹ مسیر ممیزی‌شده', `16-routes-${chapter.id}`, <RouteMatrixPage chapter={chapter} />, chapter.id % 2 === 0 ? 'soft' : 'paper')));

  add(opener(17));
  caseStudies.forEach((pair, index) => add(page('17', 'نمونه‌های محصول منتخب', `17-case-${index + 1}`, <CaseStudyPage pair={pair} index={index + 1} />, index % 2 ? 'soft' : 'paper')));

  add(opener(18));
  add(page('18', 'روشن، تیره و پاسخ‌گو', '18-themes', <><PageTitle kicker="۱۸ · Light × Dark" title="معنا ثابت، مقدار متناسب با سطح" lead="تم تیره بازطراحی جداگانه نیست؛ همان توکن‌ها مقدارهای خوانا و کنترل‌شده دریافت می‌کنند." /><div className="catalog-book-dual-figure"><ScreenshotFigure src="/catalog-book-generated/showcase-light.png" alt="مرجع طراحی در تم روشن" number="۱۸-۱" title="تم روشن" /><ScreenshotFigure src="/catalog-book-generated/showcase-dark.png" alt="مرجع طراحی در تم تیره" number="۱۸-۲" title="تم تیره" /></div><div className="catalog-book-theme-rules"><span>Typography</span><span>Service card</span><span>Form</span><span>Conversation</span><span>Financial panel</span><span>AI assistant</span></div></>));
  add(page('18', 'روشن، تیره و پاسخ‌گو', '18-responsive', <><PageTitle kicker="۱۸ · Desktop × Mobile" title="پاسخ‌گویی یعنی حفظ اولویت" lead="کنترل‌ها stack می‌شوند، مسیرهای افقی scroll می‌شوند و محتوای اصلی کوچک یا فشرده نمی‌شود." /><div className="catalog-book-phone-gallery">{[
    ['mobile-membership','عضویت زیر ۱۸ سال'],['mobile-checkout','تسویه ام‌بازار'],['mobile-transactions','تراکنش ام‌حسام'],['mobile-appointments','نوبت ام‌سلامت'],
  ].map(([image,title],index) => <ScreenshotFigure src={`/catalog-book-generated/${image}.png`} alt={title} number={`۱۸-${index+3}`} title={title} key={image} />)}</div><Callout title="breakpoint philosophy" tone="info">تمرکز روی اندازه لمس، عرض خواندن، جلوگیری از overflow و حفظ ترتیب DOM است؛ نه فقط تعداد ستون.</Callout></>));

  add(opener(19));
  add(page('19', 'دسترس‌پذیری', '19-practices', <><PageTitle kicker="۱۹ · الگوی پیاده‌سازی‌شده" title="ساختار، تعامل، متن و حرکت" lead="این فصل گواهی رسمی نیست؛ رفتارهای قابل مشاهده در مخزن را مستند می‌کند." /><RuleGrid columns={3} items={[
    { title: 'فوکوس صفحه‌کلید', code: ':focus-visible', text: 'outline واضح با offset و کنتراست مکمل.' },{ title: 'فرم معنایی', code: 'label + describedby', text: 'برچسب، راهنما و خطا به کنترل متصل‌اند.' },{ title: 'وضعیت غیررنگی', code: 'text + icon + color', text: 'رنگ تنها حامل موفقیت یا خطا نیست.' },{ title: 'dialog', code: 'aria-modal + Escape', text: 'نام، خروج با Escape و بازگرداندن فوکوس.' },{ title: 'RTL', code: 'dir="rtl" + bdi', text: 'صفحه فارسی و جزیره‌های فنی جدا.' },{ title: 'کاهش حرکت', code: 'prefers-reduced-motion', text: 'gaze و حرکت پیوسته متوقف می‌شوند.' },{ title: 'Canvas', code: 'aria-hidden', text: 'محتوای حیاتی در HTML می‌ماند.' },{ title: 'پیام خطا', code: 'aria-invalid', text: 'خطا دلیل و روش بازیابی دارد.' },{ title: 'هدف لمس', code: 'control-md 48px', text: 'کنترل‌های اصلی اندازه کافی دارند.' },
  ]} /></>));
  add(page('19', 'دسترس‌پذیری', '19-dialog-canvas', <><PageTitle kicker="۱۹ · سناریوهای پیچیده" title="مودال، sheet و Canvas" lead="تعامل‌های غنی باید مسیر ورودی و خروجی صفحه‌کلید و fallback را تعریف کنند." /><div className="catalog-book-access-scenarios"><article><h2>Dialog</h2><ol><li>نام قابل دسترس</li><li>فوکوس روی کنترل امن</li><li>Escape و کلیک backdrop</li><li>بازگشت فوکوس به trigger</li></ol></article><article><h2>Mobile sheet</h2><ol><li>ترتیب DOM منطقی</li><li>دکمه بستن دارای label</li><li>محتوای پشت غیرقابل تعامل</li><li>ارتفاع و scroll قابل کنترل</li></ol></article><article><h2>3D Canvas</h2><ol><li>پنهان از assistive tech</li><li>outer image label</li><li>fallback ایستا</li><li>کنترل‌ها و پاسخ در HTML</li></ol></article></div><Callout title="واژه‌گذاری دقیق" tone="warning">از عبارت «الگوی پیاده‌سازی‌شده» استفاده می‌شود؛ این مخزن ادعای certification یا audit رسمی WCAG ندارد.</Callout></>));

  add(opener(20));
  add(page('20', 'الگوهای وضعیت', '20-state-grid', <><PageTitle kicker="۲۰ · state matrix" title="وضعیت‌ها باید طراحی شوند" lead="هر وضعیت ترکیب متن، کنترل، اولویت و مسیر بازیابی خود را دارد." /><div className="catalog-book-state-matrix">{[
    ['default','آماده تعامل'],['hover','نشانه ثانویه'],['focus','outline واضح'],['disabled','دلیل غیرفعال'],['loading','اسکلت ساختاری'],['empty','راه بازیابی'],['success','نتیجه + ادامه'],['warning','توجه + انتخاب'],['error','دلیل + اصلاح'],['authenticated','مشاهده احراز‌شده'],['public','دانش عمومی'],['gated','درگاه مستقل'],['read-only','بدون تغییر'],['safe-stop','پیش از اثر'],['unavailable','عدم دسترسی'],['not-visible','دیده‌نشده در ممیزی'],
  ].map(([state,copy]) => <article className={`state-${state}`} key={state}><code dir="ltr">{state}</code><strong>{copy}</strong><i /></article>)}</div></>));
  add(page('20', 'الگوهای وضعیت', '20-service-states', <><PageTitle kicker="۲۰ · اکوسیستم خدمات" title="وضعیت، مجوز نیست" lead="authenticated یا public وضعیت مشاهده‌شده‌اند؛ L0 تا L3 سطح ریسک و مرز اقدام را جداگانه تعیین می‌کنند." /><div className="catalog-book-status-risk-cross"><header><span>وضعیت ممیزی</span><span>L0</span><span>L1</span><span>L2</span><span>L3</span></header>{['public','authenticated','safe-stop','gated','unavailable','not-visible'].map((status) => <div key={status}><code dir="ltr">{status}</code>{(['L0','L1','L2','L3'] as const).map((risk) => <span className={serviceCatalog.some((route) => route.verificationStatus === status && route.riskLevel === risk) ? 'used' : ''} key={risk}>{serviceCatalog.filter((route) => route.verificationStatus === status && route.riskLevel === risk).length || '—'}</span>)}</div>)}</div><Callout title="نمونه" tone="danger">یک مسیر `authenticated` می‌تواند L3 باشد؛ مشاهده پس از ورود به‌تنهایی مجوز اجرای اقدام حساس نیست.</Callout></>));

  add(opener(21));
  const inventoryChunks = Array.from({ length: 7 }, (_, index) => componentInventory.slice(index * 14, (index + 1) * 14));
  inventoryChunks.forEach((items, index) => add(page('21', 'موجودی اجزا', `21-inventory-${index + 1}`, <InventoryPage items={items} index={index + 1} />, index % 2 ? 'soft' : 'paper')));

  add(opener(22));
  add(page('22', 'معماری سیستم', '22-layers', <><PageTitle kicker="۲۲ · لایه‌های سیستم" title="از foundation تا انتشار" lead="وابستگی از عمومی به تخصصی حرکت می‌کند و نمونه‌ها مصرف‌کننده اجزای مشترک‌اند." /><div className="catalog-book-architecture-stack"><span><b>Foundation</b><small>tokens · typography · icon wrapper</small></span><i>↓</i><span><b>Core components</b><small>primitives · navigation · theme</small></span><i>↓</i><span><b>Domain compositions</b><small>AI · journeys · secure · segments · M-Bazar</small></span><i>↓</i><span><b>Examples</b><small>69 interactive audited paths</small></span><i>↓</i><strong>Catalog · Showcase · QA · Publication</strong></div></>));
  add(page('22', 'معماری سیستم', '22-data-flow', <><PageTitle kicker="۲۲ · ردپای داده" title="شواهد تا صفحه تعاملی" lead="سه رجیستری کلیدی، شواهد، هویت و route را به ترکیب قابل استفاده متصل می‌کنند." /><div className="catalog-book-data-flow"><article><code dir="ltr">service-catalog.ts</code><p>عنوان دوزبانه، وضعیت، ریسک، توقف و componentKeys</p></article><i>←</i><article><code dir="ltr">ecosystem.ts</code><p>هویت خدمت، منبع دارایی و provenance</p></article><i>←</i><article><code dir="ltr">example-route-registry.ts</code><p>route یکتا و دامنه محصول</p></article><i>←</i><article><strong>Interactive page</strong><p>ترکیب اجزا با fixture ساختگی</p></article></div><div className="catalog-book-process-diagram"><span>audit evidence</span><i>←</i><span>service identity</span><i>←</i><span>route</span><i>←</i><span>reusable components</span><i>←</i><strong>page</strong></div></>));
  add(page('22', 'معماری سیستم', '22-repo-map', <><PageTitle kicker="۲۲ · نقشه مخزن" title="مالکیت کد روشن" lead="هر خانواده در پوشه مستقل و با مرز مسئولیت قابل تشخیص نگهداری می‌شود." /><div className="catalog-book-tree" dir="ltr"><code>mresalat/</code><span>├── core/ <i>brand · icons · primitives · inventory</i></span><span>├── ai/ <i>assistant · trust · mascot</i></span><span>├── journeys/ <i>template · wizard</i></span><span>├── secure/ <i>L3 flow</i></span><span>├── segments/ + contexts/ <i>audience · relationship</i></span><span>├── mbazar/ <i>marketplace family</i></span><span>├── examples/ <i>domain compositions + route registry</i></span><span>├── domains/ <i>catalog · ecosystem · contracts</i></span><span>└── catalog-book/ <i>this publication</i></span><code>app/</code><span>├── showcase/ · catalog/ · qa/ · examples/</span><span>└── design-system-catalog/</span></div></>));

  add(opener(23));
  add(page('23', 'راهنمای استفاده برای تیم‌ها', '23-roles', <><PageTitle kicker="۲۳ · پنج مخاطب" title="یک منبع، پرسش‌های متفاوت" lead="کاتالوگ مسیر ورود هر نقش را روشن می‌کند." /><RuleGrid columns={3} items={[
    { title: 'برای طراح', text: 'توکن، جزء، حالت، RTL، responsive و مرز ریسک را همزمان تعریف کنید.' },{ title: 'برای توسعه‌دهنده', text: 'رجیستری و جزء موجود را مصرف کنید و fixture ساختگی بسازید.' },{ title: 'برای مدیر محصول', text: 'دامنه، مسیر، سطح ریسک و نقطه توقف را پیش از scope تأیید کنید.' },{ title: 'برای پیمانکار', text: 'هویت رسمی و قراردادهای طراحی را بدون fork یک‌بارمصرف رعایت کنید.' },{ title: 'برای تیم محتوا', text: 'متن فارسی روشن، منبع، قطعیت و اقدام بعدی را حفظ کنید.' },{ title: 'برای ذی‌نفع کسب‌وکار', text: 'پوشش ۱۲ دامنه و ۶۹ مسیر را بدون فرض اتصال تولید مرور کنید.' },
  ]} /></>));
  add(page('23', 'راهنمای استفاده برای تیم‌ها', '23-workflow', <><PageTitle kicker="۲۳ · workflow" title="از نیاز تا QA" lead="فرایند مشترک، کیفیت را پیش از تحویل قابل بررسی می‌کند." /><div className="catalog-book-team-workflow">{['نیاز و دامنه','توکن','جزء مشترک','ترکیب دامنه','سطح ریسک','حالت‌ها','RTL و responsive','Accessibility','QA و ممیزی'].map((step,index) => <article key={step}><span>{(index+1).toLocaleString('fa-IR')}</span><strong>{step}</strong></article>)}</div><Callout title="دروازه تحویل" tone="success">هیچ مسیر جدیدی بدون حالت خالی/خطا، مرز توقف، تست RTL، بررسی موبایل و نگاشت component inventory کامل نیست.</Callout></>));

  add(opener(24));
  add(page('24', 'بایدها و نبایدها', '24-do', <><PageTitle kicker="۲۴ · DO" title="الگو را تقویت کنید" lead="این رفتارها بلوغ و انسجام سیستم را حفظ می‌کنند." /><div className="catalog-book-do-list">{[
    ['هویت رسمی خدمت','MResalatServiceIcon و منبع دارایی را حفظ کنید.'],['مرز توقف','اثر واقعی را نام ببرید و پیش از آن متوقف شوید.'],['توکن‌ها','از نام معنایی استفاده کنید؛ مقدار را hardcode نکنید.'],['فارسی خوانا','عرض، فاصله خط و شکست واژه را بررسی کنید.'],['منبع و ریسک','trust و L0–L3 را در سطح تصمیم نشان دهید.'],['fixture ساختگی','داده قابل شناسایی را از نمونه حذف کنید.'],['جزء مشترک','پیش از ساخت جدید، inventory را جستجو کنید.'],['حالت‌ها','loading، empty، error و disabled را طراحی کنید.'],
  ].map(([title,text],index) => <article key={title}><span>✓</span><div><strong>{title}</strong><p>{text}</p></div><small>{(index+1).toLocaleString('fa-IR')}</small></article>)}</div></>));
  add(page('24', 'بایدها و نبایدها', '24-dont', <><PageTitle kicker="۲۴ · DON’T" title="یکپارچگی را نشکنید" lead="این خطاها مستقیماً از درس‌های QA و معماری جاری استخراج شده‌اند." /><div className="catalog-book-dont-list">{[
    ['آیکون عمومی به‌جای لوگو','هویت خدمت را با symbol عمومی جایگزین نکنید.'],['شکستن کلمه فارسی','Badge یا chip را مجبور به خرد شدن واژه نکنید.'],['اقدام حساس مستقیم','بدون مرور، تأیید و step-up به اجرا نروید.'],['داده واقعی در fixture','نام، حساب، سلامت، پیام یا مکان واقعی وارد نکنید.'],['جزء یک‌بارمصرف','الگوی مشترک را برای یک صفحه دوباره‌نویسی نکنید.'],['ادعای بدون شواهد','قابلیت، اتصال یا certification موجودنشده را اعلام نکنید.'],['اسکرین‌شات کشیده','تصویر دسکتاپ را برای پر کردن صفحه چاپی نخوانا نکنید.'],['وضعیت فقط رنگی','موفقیت و خطا را بدون متن یا نماد نشان ندهید.'],
  ].map(([title,text],index) => <article key={title}><span>×</span><div><strong>{title}</strong><p>{text}</p></div><small>{(index+1).toLocaleString('fa-IR')}</small></article>)}</div></>));

  return pages;
}

function Toc({ entries, starts, appendixStart }: { entries: typeof publicationSections; starts: Record<string, number>; appendixStart?: number }) {
  return <div className="catalog-book-toc"><PageTitle kicker="فهرست مطالب" title={entries[0][0] === '01' ? 'مبانی تا زمینه' : 'مسیرها تا قواعد استفاده'} lead="شماره‌ها از رجیستری ثابت صفحه محاسبه شده‌اند." />{entries.map(([number,title,english]) => <article key={number}><span>{Number(number).toLocaleString('fa-IR')}</span><div><strong>{title}</strong><bdi dir="ltr">{english}</bdi></div><i /><em>{starts[number].toLocaleString('fa-IR')}</em></article>)}{appendixStart && <article className="appendix"><span>پ</span><div><strong>پیوست‌ها و واژه‌نامه</strong><bdi dir="ltr">Appendices</bdi></div><i /><em>{appendixStart.toLocaleString('fa-IR')}</em></article>}</div>;
}

function buildAppendixPages(startPage: number): FullPageSpec[] {
  const domainRows = exampleDomains.map((domain) => ({ domain, routes: exampleRoutes.filter((route) => route.domain === domain.key) }));
  const glossary = [
    ['توکن معنایی','نام پایدار طراحی که مقدار آن بر اساس تم یا زمینه تعیین می‌شود.'],['جزیره LTR','بخش محدود چپ‌به‌راست برای route، ID، token یا کد در صفحه RTL.'],['مرز توقف','نقطه‌ای که دمو پیش از اثر واقعی، ورود، ارسال یا پرداخت متوقف می‌شود.'],['شواهد ممیزی','وضعیت مشاهده‌شده‌ای که از مجوز اقدام یا اتصال تولید جداست.'],['fixture','داده ساختگی و امن برای نمایش حالت و تعامل.'],['fallback هویت','هویت طراحی‌شده برای گروه بدون دارایی رسمی مستقل.'],['RAG','پاسخ مبتنی بر بازیابی با نمایش منبع و قطعیت.'],['step-up','احراز قوی‌تر برای ادامه اقدام حساس.'],['safe-stop','وضعیتی که اثر و مرور را نشان می‌دهد اما اجرا را انجام نمی‌دهد.'],['component inventory','رجیستری تایپ‌شده نام، هدف، گونه و حالت اجزا.'],['domain composition','ترکیب اجزای مشترک برای یک خانواده خدمت.'],['responsive','تغییر ترکیب با حفظ اولویت و ترتیب معنا در عرض‌های مختلف.'],
  ];
  return [
    page('APP', 'پیوست A · توکن‌ها', 'app-tokens', <><PageTitle kicker="پیوست A" title="نمایه توکن‌های کلیدی" lead="نام و مقدارهای چاپی از CSS جاری استخراج شده‌اند." /><div className="catalog-book-appendix-table"><div><strong>Token</strong><strong>Light</strong><strong>Dark / role</strong><strong>کاربرد</strong></div>{[...lightDarkTokens, ...brandTokens, ...trustTokens].map((token) => <article key={`${token.name}-${token.value}`}><code dir="ltr">{token.name}</code><bdi dir="ltr">{token.value}</bdi><bdi dir="ltr">{'darkValue' in token ? token.darkValue : 'semantic role'}</bdi><p>{token.usage}</p></article>)}</div></>, 'soft'),
    page('APP', 'پیوست B · ریسک', 'app-risk', <><PageTitle kicker="پیوست B" title="ماتریس ریسک و توقف" lead="سطح، الگوی تعامل، کنترل و نمونه route در یک نگاه." /><div className="catalog-book-appendix-risk">{(['L0','L1','L2','L3'] as const).map((risk) => { const routes = serviceCatalog.filter((route) => route.riskLevel === risk); return <article key={risk}><RiskBadge level={risk} /><div><strong>{risk === 'L0' ? 'دانش عمومی' : risk === 'L1' ? 'مشاهده احراز‌شده' : risk === 'L2' ? 'اقدام کنترل‌شده' : 'اقدام حساس'}</strong><p>{routes[0].safeStopFa}</p><code dir="ltr">{routes.slice(0,4).map((route) => route.demoHref).join('\n')}</code></div><span>{routes.length.toLocaleString('fa-IR')} مسیر</span></article>})}</div></>),
    page('APP', 'پیوست C · هویت خدمات', 'app-identities', <><PageTitle kicker="پیوست C" title="ماتریس هویت خدمات" lead="تمام ۱۷ هویت با نوع دارایی و provenance ثبت شده‌اند." /><div className="catalog-book-identity-matrix">{ecosystemIdentityServices.map((service) => <article key={service.id}><MResalatServiceIcon service={service} size={40} /><div><strong>{service.titleFa}</strong><bdi dir="ltr">{service.id}</bdi></div><span>{service.identity.source === 'official-asset' ? 'رسمی' : 'طراحی‌شده'}</span><code dir="ltr">{service.identity.asset ?? service.identity.glyph}</code></article>)}</div><footer className="catalog-book-matrix-summary"><Stat value={14} label="دارایی رسمی" /><Stat value={3} label="fallback طراحی‌شده" /><Stat value={17} label="کل هویت‌ها" /></footer></>),
    page('APP', 'پیوست D · نمایه دامنه و route', 'app-domain-index', <><PageTitle kicker="پیوست D" title="نمایه دامنه، route و ریسک" lead="ورودی هر دامنه و توزیع مسیرهای آن برای ارجاع سریع." /><div className="catalog-book-domain-index">{domainRows.map(({domain,routes},index) => <article key={domain.key}><span>{(index+1).toLocaleString('fa-IR')}</span><div><strong>{domain.titleFa}</strong><bdi dir="ltr">{domain.href}</bdi></div><em>{routes.length.toLocaleString('fa-IR')} مسیر</em><small>{[...new Set(routes.map((route) => serviceCatalog.find((item) => item.id === route.serviceId)?.riskLevel))].join(' · ')}</small></article>)}</div><Callout title="کنترل پوشش" tone="success">مجموع همه ردیف‌ها ۶۹ است و هر serviceId دقیقاً یک example route دارد.</Callout></>),
    page('APP', 'پیوست E · واژه‌نامه', 'app-glossary', <><PageTitle kicker="پیوست E" title="واژه‌نامه فارسی سیستم" lead="تعریف کوتاه اصطلاحات پرکاربرد این انتشار." /><div className="catalog-book-glossary">{glossary.map(([term,definition],index) => <article key={term}><span>{(index+1).toLocaleString('fa-IR')}</span><strong>{term}</strong><p>{definition}</p></article>)}</div><div className="catalog-book-colophon"><BrandLockup compact /><div><strong>پایان کاتالوگ</strong><p>این سند از کد جاری MResalat System تولید، با Chromium صادر و صفحه‌به‌صفحه بازبینی شده است.</p><bdi dir="ltr">{catalogBookMeta.repository} · {catalogBookMeta.version} · {catalogBookMeta.generatedAt}</bdi></div><em>{startPage.toLocaleString('fa-IR')}–{(startPage+4).toLocaleString('fa-IR')}</em></div></>),
  ];
}

export function buildFullCatalogBookSpecs(): FullPageSpec[] {
  const sectionPages = buildSectionPages();
  const starts = Object.fromEntries(publicationSections.map(([number]) => [number, 7 + sectionPages.findIndex((item) => item.sectionKey === number)]));
  const appendixStart = 7 + sectionPages.length;
  const front: FullPageSpec[] = [
    page('FRONT', 'صفحه عنوان', 'front-title', <div className="catalog-book-inner-title"><BrandLockup /><div><span>انتشار فارسی · نسخه کد-محور</span><h1>{catalogBookMeta.title}</h1><p>{catalogBookMeta.subtitle}</p><bdi dir="ltr">MResalat Design System Catalog · FA · {catalogBookMeta.version}</bdi></div><footer><strong>بانک قرض‌الحسنه رسالت</strong><span>MResalat System</span><em>{catalogBookMeta.generatedAt}</em></footer></div>),
    page('FRONT', 'اطلاعات سند', 'front-info', <><PageTitle kicker="اطلاعات انتشار" title="سندی زنده از سیستم کدنویسی‌شده" lead="این PDF از مسیر اختصاصی React و داده‌های رجیستری جاری تولید شده است." /><div className="catalog-book-document-info"><article><span>نسخه</span><bdi dir="ltr">{catalogBookMeta.version}</bdi></article><article><span>مخزن</span><bdi dir="ltr">{catalogBookMeta.repository}</bdi></article><article><span>مبدأ</span><bdi dir="ltr">{catalogBookMeta.commitBase}</bdi></article><article><span>تاریخ</span><strong>{catalogBookMeta.generatedAt}</strong></article><article><span>زبان</span><bdi dir="ltr">fa-IR · RTL</bdi></article><article><span>قالب</span><bdi dir="ltr">A4 portrait · print-ready</bdi></article></div><RuleGrid columns={3} items={[{ title: 'دامنه', text: 'foundations، اجزا، AI، اعتماد، ریسک، سگمنت، ۱۲ دامنه و ۶۹ مسیر.' },{ title: 'منبع حقیقت', text: 'کد، CSS، رجیستری‌ها، نمونه‌های تعاملی و inventory جاری.' },{ title: 'محدودیت', text: 'بدون اتصال تولید، داده واقعی یا ادعای certification.' }]} /></>),
    page('FRONT', 'مقدمه اجرایی', 'front-executive', <><PageTitle kicker="مقدمه اجرایی" title="یک زبان تجربه برای اکوسیستم فارسی" lead="MResalat System یک سیستم Persian-first، RTL-first و code-first برای تجربه‌های مالی و اکوسیستمی است." /><EditorialColumns><div><p className="catalog-book-dropcap">این سیستم طراحی، هویت بصری، اجزا، الگوهای فرایند، زمینه مخاطب و سیاست‌های اعتماد و ریسک را به کد قابل استفاده تبدیل می‌کند. هدف آن ایجاد صفحه‌های مشابه نیست؛ هدف، ساخت تجربه‌های هم‌خانواده با زبان تصمیم مشترک است.</p><p>طراح، توسعه‌دهنده و مدیر محصول از یک مجموعه توکن، موجودی اجزا و رجیستری مسیر استفاده می‌کنند. پیمانکار می‌تواند مرز دارایی رسمی و fallback را ببیند و ذی‌نفع کسب‌وکار می‌تواند پوشش دامنه و مسیر را بدون ورود به جزئیات کد بررسی کند.</p></div><div className="catalog-book-metric-wall"><Stat value={catalogBookFacts.components} label="اجزای ثبت‌شده" /><Stat value={catalogBookFacts.routes} label="مسیر ممیزی‌شده" /><Stat value={catalogBookFacts.domains} label="دامنه محصول" /><Stat value={catalogBookFacts.identities} label="هویت خدمت" /><Stat value={10} label="سگمنت مخاطب" /><Stat value="L0–L3" label="مدل ریسک" /></div></EditorialColumns><Callout title="Persian-first" tone="success">زبان، عدد، جهت، شکست خط و آمیختگی رشته‌های فنی از ابتدا بخشی از معماری تجربه‌اند.</Callout></>),
    page('FRONT', 'راهنمای استفاده', 'front-use', <><PageTitle kicker="چگونه از این کاتالوگ استفاده کنیم" title="از پرسش نقش خود آغاز کنید" lead="فصل‌ها هم برای مرور اجرایی و هم برای ارجاع فنی طراحی شده‌اند." /><RuleGrid columns={3} items={[{ title: 'طراح', text: 'مبانی، هویت، اجزا، responsive، accessibility و DO/DON’T را مرور کنید.' },{ title: 'توسعه‌دهنده', text: 'نام component، token، state، route و architecture را دنبال کنید.' },{ title: 'محصول', text: 'دامنه، case study، risk و safe-stop را به scope متصل کنید.' },{ title: 'پیمانکار', text: 'قواعد برند، service identity و component inventory را مرجع قرار دهید.' },{ title: 'محتوا', text: 'زبان اعتماد، قطعیت، منبع، خطا و اقدام بعدی را استفاده کنید.' },{ title: 'مدیر اجرایی', text: 'فصل‌های ۱۵ تا ۱۷ پوشش محصول و شواهد ۶۹ مسیر را خلاصه می‌کنند.' }]} /><div className="catalog-book-reading-paths"><span>مرور ۱۵ دقیقه‌ای: مقدمه ← ۱۲ دامنه ← ۶۹ مسیر ← معماری</span><span>مرور طراحی: مبانی ← رنگ ← تایپوگرافی ← اجزا ← دسترس‌پذیری</span><span>مرور مهندسی: inventory ← architecture ← route matrix ← appendices</span></div></>),
    page('FRONT', 'فهرست مطالب', 'front-toc-a', <Toc entries={publicationSections.slice(0,12) as unknown as typeof publicationSections} starts={starts} />, 'soft'),
    page('FRONT', 'فهرست مطالب', 'front-toc-b', <Toc entries={publicationSections.slice(12) as unknown as typeof publicationSections} starts={starts} appendixStart={appendixStart} />, 'soft'),
  ];
  return [...front, ...sectionPages, ...buildAppendixPages(appendixStart)];
}

export const FULL_CATALOG_PAGE_COUNT = 1 + buildFullCatalogBookSpecs().length;

export function getFullCatalogOutline() {
  const specs = buildFullCatalogBookSpecs();
  const seen = new Set<string>();
  const outline = [{ title: 'جلد', pageIndex: 0 }, { title: 'مقدمه و فهرست', pageIndex: 1 }];
  specs.forEach((item, index) => {
    if (item.sectionKey === 'FRONT' || seen.has(item.sectionKey)) return;
    seen.add(item.sectionKey);
    outline.push({ title: item.sectionKey === 'APP' ? 'پیوست‌ها' : item.sectionTitle, pageIndex: index + 1 });
  });
  return outline;
}
